### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by zfred68** [arduino/arduino-ide#110]
I downloaded the package for linux, there's a shared library file arduino-pro-ide. Then what? There is no readme file
listing what pre-requisites are required, or INSTALL.txt of how to install. So I just learned something about Theia, sure
so it seems I need to catchup with some stuff, but how far down the rabbit hole must one go to figure out how to try this
out. Is it too much to ask for whoever to describe the steps to get going. Oh i've read the github head page, a few times,
its still not helping.

**Is your feature request related to a problem? Please describe.**
A It is a problem when there are no clear instructions for some new tech that is happening, very frustrating.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by per1234** [comment]
We now have documentation for installing Arduino IDE 2.x:

https://docs.arduino.cc/software/ide-v2/tutorials/getting-started/ide-v2-downloading-and-installing#linux

The remaining work that needs to be done to resolve this request is refining those instructions so that it is clear that the IDE must be started from the command line on Linux. At the moment, the documentation implies that it can be opened via the file browser.

**Comment by per1234** [comment]
Installation instructions are now finalized. Thanks for the feedback everyone!
