### ISSUE TITLE
Remove Editor tabs contextual menu

### ISSUE THREAD

**Issue by francescospissu** [arduino/arduino-ide#1127]
Right-clicking on a tab in the editor displays a contextual menu

![CleanShot 2021-12-28 at 12.57.45.png](https://zube.io/files/arduino/c4d1af3cb2c23c57c85fa577b1ea0639-cleanshot-2021-12-28-at-12-57-45.png)

This allows users to maximise the editor tab (see Zen Mode) and to reveal in the Theia Explorer.
The Theia Explorer cannot be removed from the sidebar causing further issues.

Entirely disabling this contextual menu would save us a lot of o headaches

**Comment by per1234** [comment]
The context menu items shown in the screenshot above have been removed since the time it was taken (https://github.com/arduino/arduino-ide/pull/940). The menu now looks like this:

![image](https://user-images.githubusercontent.com/8572152/176460700-68ec3685-77ef-4776-9970-ea9fd60279ce.png)

Since an empty context menu serves no purpose, removing it entirely will enhance the Arduino IDE UI.
