### ISSUE TITLE
Restrict the app to one instance

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#114]
Due to this: https://github.com/eclipse-theia/theia/issues/7983

Users will be still able to open multiple browser windows (per sketches) for the same process, but they will **NOT** be able to start the Pro IDE twice.

**Comment by CreativeRobotics** [comment]
I routinely work with several microcontrollers at once, working on code that communicates between them. The ability to run two or more instances at once, and have each instance connected to a different communication port for programming and serial debugging is an essential feature for a 'pro' IDE. Having the ability to open multiple sketches, but then having to select different boards and comm ports when dealing with each sketch is a bug in my view.

**Comment by mklemarczyk** [comment]
I moved to IDE 2.0 only because I can open multiple instances of Arduino IDE. If that feature is gone, I have noting to do here and I can as well use the old Arduino IDE 1.0.

I usually work with multiple boards and projects on Arduino IDE. If you restrict it to one instance it will be a huge drawback. Any other IDE like Visual Studio, or industrial EcoStruxure Control Expert are not having such limitation.

**Comment by kittaakos** [comment]
> If you restrict it to one instance it will be a huge drawback. Any other IDE like Visual Studio, or industrial EcoStruxure Control Expert are not having such limitation.

Thanks for your remark.

For clarification: single instance != single window.

Even if a single instance IDE2 app is running, it will be possible to open multiple windows and work on various sketches just as it is now.

**Comment by kittaakos** [comment]
Closing. IDE2 has been using the `singleInstance` config for a long time ago: https://github.com/arduino/arduino-ide/blob/d79bc0d083c40b3244264696d2d6703756a8bd53/electron/build/patch/backend/main.js#L33
