### ISSUE TITLE
I don't think nighly-build-verification should be necessary when submitting issues

### ISSUE THREAD

**Issue by Silver-Fang** [arduino/arduino-ide#1211]
### Describe the request

- You can ask the submitter to search for duplicate issues first. If there are no duplicates, the probability that this issue happens to be fixed in a nightly build is extremely low.
- Installing and uninstalling an Arduino IDE is not a simple task that can be done in a minute. This requirement will dissuade a considerable number of potential feedbacks, while others will simply tick the box without actually verifying the nightly build.
- I know it's very irritating to deal with duplicate and resolved issues. But that should at least be better than missing out on really valuable feedback.

### Describe the current behavior

You're required to tick the box saying you've tried with the latest nightly build.

### Arduino IDE version

Not an IDE issue

### Operating system

N/A

### Operating system version

N/A

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @Silver-Fang. Thanks for your suggestion.

>Installing and uninstalling an Arduino IDE is not a simple task that can be done in a minute.

This is a free open source project. Huge amounts of resources are dedicated to creating a gift for all the world. The nightly builds are very accessible. So I don't think it is too much to ask for contributors to make the effort to ensure their report is of value, rather than a burden that prevents the team from being productive.

>the probability that this issue happens to be fixed in a nightly build is extremely low.

My experience from ~7 years of maintaining issue trackers of Arduino projects says otherwise. 

>that should at least be better than missing out on really valuable feedback.

There are limits to our bandwidth for feedback. We are well over that limit already even with the restriction.

Filtering out low quality feedback from the users who won't make the effort to test with the nightly allows us to focus on the high quality feedback from conscientious contributors.
