### ISSUE TITLE
Network port support

### ISSUE THREAD

**Issue by tomlevels** [arduino/arduino-ide#123]
I'm not sure if it is a bug or if it is just not implemented yet, but it seems I cannot select any network ports. It would be great if this was supported since I regularly update some of my devices OTA.

**Comment by rtek1000** [comment]
Hello guys, I don't want to be too boring, but it will be difficult for people to test this IDE 2.0 if they don't have the network port.

Do you have any expectations of being able to add this functionality?

Do you have any priority of adding this network port?

Thank you.

**Comment by mcquaas** [comment]
I have over 20 devices (esp32's and esp8266's) connected at home, all updated via OTA. Without network ports I can't work with Arduino IDE 2.0.

Worst thing is, Arduino 1.x still doesn't work with Big Sur (I know, blame Apple for it). 

It would be really great to have this feature implemented soon.

Any news?

**Comment by Shashank-Prasanna** [comment]
This would be awesome. The only reason I am not using this IDE right now a lot is because most of my code needs to be uploaded over a network port. Any ETA on when we can expect network ports?

**Comment by mcspr** [comment]
Network ports are displayed and working (?) in the app since beta12, but we got report at esp8266/Arduino that only IP addresses are displayed
https://github.com/esp8266/Arduino/issues/8344

Instead of something like 'MyCustomBoard at 1.2.3.4'. But, not sure which part is at fault here - arduino-cli, mdns-discovery tool or the ide itself
