### ISSUE TITLE
"Create Desktop Entry" Feature

### ISSUE THREAD

**Issue by javidizadi** [arduino/arduino-ide#1246]
### Describe the request

It can cause bee better if we have a menu option to create desktop entries for the Linux version, same as the IntelliJ IDEs.
![image](https://user-images.githubusercontent.com/74705231/180618561-e9d5d5a7-d0f7-48dc-944f-e06e19c56cfc.png)
### 

### Describe the current behavior

any options to add a Desktop entry in the Linux version don't exist, and I should manually create it.

### Arduino IDE version

2.0.0-rc9

### Operating system

Linux

### Operating system version

5.18.12-zen

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Thanks for your request @javidizadi. Although it might be a reasonable design decision for the JetBrains products, the design of the Arduino IDE is intended to avoid any unnecessary complexity in the user interface in order to make it as approachable as possible to all users. In this case, adding a menu item that will only ever be used once doesn't make sense.

Better would be to provide such a capability from outside the application, such as by an installer of some sort.

Related: https://github.com/arduino/arduino-ide/pull/356
