### ISSUE TITLE
Arduino IDE 2.0.0-rc9: Input in Serial Monitor is not working

### ISSUE THREAD

**Issue by sourkarm2** [arduino/arduino-ide#1248]
### Describe the problem

I am using Arduino Due in windows 11. In my code, I have to give some input in the serial monitor to run the sketch, but when I provide the desired input and press Ctrl+Enter, input data is not getting accepted by the code. Am I doing something wrong?

Everything works perfectly when I do the same thing without any change in IDE 1.8.19. Is it a bug or am I doing something wrong?

I welcome any suggestions.

### To reproduce

It happens every time I try a similar code.

### Expected behavior

Input should be accepted by the code and should do further calculation and execute.

### Arduino IDE version

IDE 2.0.0-rc9

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @sourkarm2. I am following your topic over on the Arduino Forum:

https://forum.arduino.cc/t/arduino-ide-2-0-0-rc9-input-in-serial-monitor-is-not-working/1015720

Since this issue report does not contain sufficient information, I will close it and offer support over on the forum after you have provided the requested information. If we eventually find that the problem results from an untracked bug in the Arduino IDE, I'll be sure to reopen this.
