### ISSUE TITLE
Save dialog when closing app without changing sketches

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-ide#1274]
### Describe the problem

The save dialog comes up when closing the app even when there are no changes in the sketch.

### To reproduce

Open the app, then close immediately without any changes to the sketches.

### Expected behavior

The save dialog on closing app should only appear when sketch are edited. 

### Arduino IDE version

Version: 2.0.0-rc9-nightly-20220802 Date: 2022-08-02T03:47:07.580Z CLI Version: 0.25.1 [436f0bb9]  Copyright © 2022 Arduino SA

### Operating system

macOS

### Operating system version

12.5

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
Related: https://github.com/arduino/arduino-ide/issues/1016
Breaking change: https://github.com/arduino/arduino-ide/commit/5b486b148080d67432b3373142e422dbe65effb5#diff-d75767495b70f0c6a10456f6a08ea71728c0b74709a2b697e88b9b50f6890177L65.

The current logic does not check if the document was ever touched.

**Comment by per1234** [comment]
Thanks for your report @sstaub. Please confirm whether this issue is specific to new sketches, or whether you also experience it when the unchanged sketch is saved in a normal location on disk.

I can only reproduce the issue with new sketches.

Please note that Arduino IDE 2.x opens example sketches as a sketch, so the issue also occurs with those sketches (as was previously reported at https://github.com/arduino/arduino-ide/issues/1026).

**Comment by sstaub** [comment]
I can confirm that this issue is specific to new sketches. On other saved sketches it works as expected.

**Comment by InstantMuffin** [comment]
Maybe in a way related to #1294?
