### ISSUE TITLE
Serial Plotter - Set maximum dataset points

### ISSUE THREAD

**Issue by InstantMuffin** [arduino/arduino-ide#1308]
### Describe the request

I would love for the Serial Plotter to show more than just the last 50 dataset points as it currently does.
I have not found an option to set this, and I believe a simple slider (from lets say 10-500) would do.

EDIT:
I would love to do this myself, and I think just changing the buffer's size statically is as easy as altering this line:
https://github.com/arduino/arduino-serial-plotter-webapp/blob/04a460e0c21609a63c4064f561990c0128c5a0ed/src/ChartPlotter.tsx#L46
However upon finding this I noticed that this is actually its own app with its own repo and I am not sure how to inject an altered dependency/module when compiling arduino-ide (I assume it somehow fetches these apps as packages stuffed into respective singular files as a simple file search doesn't yield any results).
That said it raises the question if this issue is best opened here, or if I should repost this in the app's repo. I apologize for any inconvenience opening this issue here might have caused.

### Describe the current behavior

The Serial Plotter currently only plots the last 50 dataset points.

### Arduino IDE version

"All of them"

### Operating system

N/A

### Operating system version

XUbuntu 22.04 LTS

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @InstantMuffin . Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/803.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

>it raises the question if this issue is best opened here, or if I should repost this in the app's repo.

It is a good question. I don't have enough knowledge about [**arduino-serial-plotter-webapp**](https://github.com/arduino/arduino-serial-plotter-webapp) to say whether this proposal would be implemented purely in its code base, or whether changes are also needed in the Arduino IDE code base.

If the former, I would like to transfer the issue to the other repository (GitHub now has a feature to allow those with write permissions to do that instead of having to re-create the issue).

>I am not sure how to inject an altered dependency/module when compiling arduino-ide (I assume it somehow fetches these apps as packages stuffed into respective singular files

Perhaps it indicates an area for improvement in the Arduino IDE documentation.
