### ISSUE TITLE
IDE2 nighty build should show the exact CLI version instead of `CLI Version: 0.0.0-git []`

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#1313]
### Describe the request

The IDE2 nightly might use a not yet released CLI version. In such a case, the CLI version is `CLI Version: 0.0.0-git []` which is not informative when accessed from the `About` dialog. IDE2 should parse the `package.json`, get the `version` object, and show the pinned CLI version instead of `0.0.0-git`.

<img width="272" alt="Screen Shot 2022-08-10 at 11 11 28" src="https://user-images.githubusercontent.com/1405703/183863151-4b32043f-9f57-414c-8380-35de4dfef8c6.png">

### Describe the current behavior

See description.

### Arduino IDE version

Version: 2.0.0-rc9.1-nightly-20220809 Date: 2022-08-09T03:33:26.061Z CLI Version: 0.0.0-git []

### Operating system

macOS

### Operating system version

13.2.1

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
The better resolution would be to use the correct method of building Arduino CLI:

https://arduino.github.io/arduino-cli/dev/CONTRIBUTING/#building-the-source-code

Arduino IDE is currently using an unsupported approach to building Arduino CLI:

https://github.com/arduino/arduino-ide/blob/8a1cabd2bcfcba822eca60a534058a2fe426234d/arduino-ide-extension/scripts/utils.js#L65

The missing version information is fairly innocuous, but it is possible this approach might cause other problems since we assume `task build` will always be used.

**Comment by kittaakos** [comment]
> The better resolution would be to use the correct method of building Arduino CLI:

If IDE2 uses `task build` instead of `go build` will the `arduino-cli version` show that the CLI was created from a fork when it was made from a fork?

**Comment by per1234** [comment]
It will only show the short hash:

```text
$ arduino-cli version --format json
{
  "Application": "arduino-cli.exe",
  "VersionString": "git-snapshot",
  "Commit": "869c9711",
  "Status": "",
  "Date": "2022-08-10T09:40:36Z"
}
```

I think it is sufficient to identify the version in use.
