### ISSUE TITLE
add deb option to download

### ISSUE THREAD

**Issue by integrated-circuit** [arduino/arduino-ide#1417]
### Describe the request

Currently, the only way to install IDE 2.0 is with appimage or flatpak. Both aren't supported by the existing extension for vs code
(flatpak containerisation, Appimage not working). A deb could also be easier to install.

### Describe the current behavior

Imposible to use the vscode/arduino extension with IDE 2.0 event with path set.

### Arduino IDE version

2.0rc9.4

### Operating system

Linux

### Operating system version

ubuntu 22.04

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @integrated-circuit

>Imposible to use the vscode/arduino extension with IDE 2.0 event with path set.

The reason for this lack of compatibility of Arduino IDE 2.x with [Microsoft's "**Visual Studio Code extension for Arduino**"](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino) is that the extension is designed for use with [the Arduino IDE 1.x command line interface](https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc).

The Arduino IDE 2.x application does not have a command line interface, so it will never be compatible with the extension, even if the IDE was distributed as a deb.

However, both the lack of a command line interface in Arduino IDE 2.x and the lack of compatibility between Arduino IDE 2.x and the extension are no problem. The reason is that Arduino has created a dedicated command line tool named [**Arduino CLI**](https://arduino.github.io/arduino-cli/latest/) which is far more powerful and more user friendly than the Arduino IDE 1.x command line.

The "**Visual Studio Code extension for Arduino**" has support for use with Arduino CLI in addition to Arduino IDE 1.x, so you can simply install Arduino CLI and then configure the extension to use it. Microsoft provides documentation for doing that here:

https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino#arduino-cli
