### ISSUE TITLE
Collapse all side panels also collapses bottom panel

### ISSUE THREAD

**Issue by mdxtinkernick** [arduino/arduino-ide#143]
**Describe the bug**
When bottom panel is visible, selecting Collapse Side Panels in View menu (or using keyboard shortcut) closes bottom panel

**To Reproduce**
1. Go to 'View'
2. Click on 'Toggle Bottom Panel' if it is not already visible
3. Go to 'View'
4. Click on 'Collapse All Side Panels'
5 Bottom Panel closes

**Expected behavior**
Would expect bottom panel to not change as it is doesn't seem to be a side panel. Either change menu entry to 'Collapse All Panels' (if it does collapse all possible panels), or change behaviour to not change Bottom Panel  

**Desktop (please complete the following information):**
 - OS: Mac High Sierra  - Version: 10.13.6 
- Arduino Pro version: 0.0.1

**Comment by per1234** [comment]
The "Collapse All Side Panels" command is no longer presented via the Arduino IDE 2.x primary UI, which I will consider as much mitigation of the issue as is reasonable to do via this project.

Since the issue of the mismatch in command name vs. behavior has already been reported in Theia, where the true fix should be made, I'll close this issue. The fix in Theia will propagate to Arduino IDE 2.x without the need for any special measures here.
