### ISSUE TITLE
When uninstalling a library, also uninstall dependent libraries

### ISSUE THREAD

**Issue by MicSG-dev** [arduino/arduino-ide#1432]
### Describe the request

When uninstalling a library that depends on other libraries, it would be nice if you had the possibility to uninstall all of them. Example: If library 1 needs library 2 and 3 as dependents, when trying to uninstall library 1 you should also uninstall libraries 2 and 3 (if other libraries do not depend on 2 and 3 ).

### Describe the current behavior

Currently, only library 1 can be uninstalled. Libraries 2 and 3 are not uninstalled.

### Arduino IDE version

Version: 2.0.0 Date: 2022-09-14T07:06:37.759Z

### Operating system

Windows

### Operating system version

Windows 7

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by ubidefeo** [comment]
@MicSG-dev 
unfortunately while the library dependencies are a useful facility when it comes to installing a library, we have no way of knowing wether a library has been installed as a dependency or the user willingly chose to install that.
We do not keep a local database of that, and it would be too convoluted and mostly unnecessary.

Imagine the scenario in which a user installs two libraries by Adafruit which both depend on BusIO.
If I uninstall one of the two the second one will be missing a dependency and since we have no ways of automatically installing a dependency, the build would fail and the user would need to manually reinstall BusIO.

I'm afraid this enhancement is not something we'll be willing to invest development time on, since it would spiral into having to completely redesign and implement how we track libraries installation.

Thank you for pitching it, though, it's always appreciated and food for thought.
I'll close this issue but I'll be waiting for your feedback or acknowledgement

u.
