### ISSUE TITLE
Cannot add Additional Board Manager URLs

### ISSUE THREAD

**Issue by mevdev** [arduino/arduino-ide#1444]
### Describe the problem

The Arduino IDE 2.0 or nightly is not able to accept any Additional Board Manager URLs.

It appears that they need to be selected from a list which is compressed into about 10 points height.
The modal window is not resizeable. The text area for 'additional URLs..' is resizable but does not aid.

### To reproduce

macOS Monterey 12.5.1
Apple Silicon 16" Macbook Pro

Download 2.0 or nightly and try to put in a URL. The 'OK' button is never enabled.
If you hit the button on the right of the textfield (two windows overlapping), it brings up a window
<img width="1128" alt="Screen Shot 2022-09-15 at 1 16 17 PM" src="https://user-images.githubusercontent.com/2013678/190500324-039b6d44-4049-4974-9577-54ef505d9e65.png">

You are not able to view the content in the dark grey line (which is probably a table view list).

<img width="808" alt="Screen Shot 2022-09-15 at 1 16 35 PM" src="https://user-images.githubusercontent.com/2013678/190500377-d2f5081b-449f-46ce-8d6e-4825f18a0ff7.png">
No urls from this supported list are accepted: https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls

When you click 'OK' to dismiss that modal the Preferences window's OK button is not enabled.

### Expected behavior

Expected to put in an additional Board Manager URL and have support for third party boards.

### Arduino IDE version

2.0

### Operating system

macOS

### Operating system version

12.5.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @mevdev. Thanks so much for your report.

>You are not able to view the content in the dark grey line (which is probably a table view list).

No, this is a horizontal scroll bar. There are some problems with the Arduino IDE UI layout related to relative sizing of various elements (https://github.com/arduino/arduino-ide/issues/1350), fixes for some of which are already in progress (https://github.com/arduino/arduino-ide/pull/1406). I have added a note about this specific bug to https://github.com/arduino/arduino-ide/issues/1350 so that we can make sure it is fixed along with the other issues reported there. However, even though this is not an ideal layout, it does not in any way break the functionality of this dialog.

>When you click 'OK' to dismiss that modal the Preferences window's OK button is not enabled.

The reason for this is completely unrelated to the "Additional Boards Manager URLs" preference. You can see the reason here:

![image](https://user-images.githubusercontent.com/8572152/190555855-1f2b2399-d29a-43cf-a59d-bfa55f9c92ac.png)

The "OK" button is disabled when the path set in the "**Sketchbook location**" preference does not exist.

There is currently a bug in the Arduino IDE that causes it to not automatically create this folder (https://github.com/arduino/arduino-ide/issues/1445).

The solution is for you to manually create an empty folder at this path:

1. If you still have the "**Preferences**" dialog open in the Arduino IDE, click the "**CANCEL**" button.
   **ⓘ** This is necessary to avoid another bug in the dialog: https://github.com/arduino/arduino-ide/issues/1259
1. Create an empty folder at this path:
   ```text
   /Users/robert/Documents/Arduino
   ```
   **ⓘ** You can use your file manager program to create this folder, or `mkdir /Users/robert/Documents/Arduino` from the command line terminal if you prefer.
1. Select **File > Preferences** from the Arduino IDE menus.
1. Configure the "**Additional Board Manager URLs**" preference as before.

This time, you should find that the "**OK**" button is enabled and that you can successfully set this preference and any others.

Since we have dedicated issues for each of the specific issues highlighted by this report, I'll go ahead and close this, but I will continue to monitor the thread. Please let me know if you have any questions or problems while following those instructions.
