### ISSUE TITLE
Settings could not be saved.

### ISSUE THREAD

**Issue by stevezh1998** [arduino/arduino-ide#1457]
### 设置界面修改后无法保存问题。
Unable to save preference.
![Snipaste_2022-09-18_17-25-58](https://user-images.githubusercontent.com/35161621/190895339-f6a006b3-a60a-420c-afb7-b4bfa47619a8.png)
![Snipaste_2022-09-18_17-50-53](https://user-images.githubusercontent.com/35161621/190896346-8e6b1be3-bd97-443c-8b6c-a6f235a4260d.png)
![Uploading Snipaste_2022-09-18_17-50-53.png…]()

### To reproduce

我是首次安装出现的这个问题。

### Expected behavior

无法保存设置。

### Arduino IDE version

2.0.0

### Operating system

Windows

### Operating system version

win10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @stevezh1998. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1445.

I'm happy to tell you that a fix is already in progress: https://github.com/arduino/arduino-ide/pull/1448

---

I'll share instructions for working around the bug:

1. If you still have the "**Preferences**" dialog open in the Arduino IDE, click the "**CANCEL**" button.
   **ⓘ** This is necessary to avoid another bug in the dialog: [#1259](https://github.com/arduino/arduino-ide/issues/1259)
1. Create an empty folder at this path:
   ```text
   d:\Users\Documents\Arduino
   ```
   **ⓘ** You can use the Windows "**File Explorer**" to create this folder.
1. Select **File > Preferences** from the Arduino IDE menus.
1. Configure the "**Language**" preference as before.

You will now be able to click the "**OK**" button since the sketchbook folder exists.

---

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
