### ISSUE TITLE
Completely unusable on macOS 12.6 in larger project

### ISSUE THREAD

**Issue by Frisch12** [arduino/arduino-ide#1460]
### Describe the problem

The IDE is completely unusable on macOS 12.6 when opening larger projects, with larger files (e.g. https://github.com/justcallmekoko/ESP32Marauder)

### To reproduce

Open https://github.com/justcallmekoko/ESP32Marauder/tree/master/esp32_marauder

### Expected behavior

IDE should respond quickly on inputs

### Arduino IDE version

2.0.0

### Operating system

macOS

### Operating system version

12.6 (on M1 Max)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @Frisch12. This bug is being tracked here: https://github.com/arduino/arduino-ide/issues/1343

I'm happy to tell you that a fix is already in progress: https://github.com/arduino/arduino-ide/pull/1450

You can easily apply that fix immediately in your Arduino IDE by a simple adjustment to the IDE's [advanced settings](https://github.com/arduino/arduino-ide/blob/main/docs/advanced-usage.md#advanced-settings). I'll provide instructions:

1. If you still have the problematic "**esp32_marauder**" sketch open in the Arduino IDE, select **File > New** from the IDE's menus and then close the window with the "**esp32_marauder**" sketch open.
1. Open the "**Command Palette**" via the <kbd>**Ctrl**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> shortcut (<kbd>**Command**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> for macOS users).
1. Select the "**Preferences: Open Settings (UI)**" command from the "**Command Palette**".
   This will open the "**Preferences**" tab in the IDE.
1. In the "**Search Settings**" field, type `editor.maxTokenizationLineLength`
1. Change the value of the "**Editor: Max Tokenization Line Length**" setting from the default `20000` to `500`
1. Close the "**Preferences**" tab by clicking its **X** icon.

You should now be able to open the "**esp32_marauder**" sketch again without experiencing those performance problems.

---

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
