### ISSUE TITLE
Sketch > Export compiled Binary

### ISSUE THREAD

**Issue by Jens869** [arduino/arduino-ide#1506]
### Describe the problem

the bin file is found in:

```text
/private/var/folders/gm/4sy77v7s78v5sl_h8jhx7p6w0000gn/T/arduino-sketch-352F5EAEA50A9FC581E2424D67B8F822/VFD-8266-Uhr.ino.bin
```

but not in:

```text
/Users/-username-/Documents/Arduino/VFD-8266-Uhr/VFD-8266-Uhr.ino.bin
```

the subfolder is hard to reach

But it old Arduino IDE 1.x puts it in the right folder !

### To reproduce

1. install Arduino IDE 2.0 on Mac
1. load an example
1. press the keys: <kbd>Alt</kbd>+<kbd>Cmd</kbd>+<kbd>S</kbd> (**Sketch > Export compiled Binary**)

### Expected behavior

place bin file in sketch folder

### Arduino IDE version

2.0.0

### Operating system

macOS

### Operating system version

MacOS 11.6.8 Intel

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
The reason it is saved to that temporary folder is because the Arduino IDE 2.x opens example code in a temporary new sketch (as discussed at https://github.com/arduino/arduino-ide/issues/925). The IDE does this because example sketches are intended to be treated as "read-only" so that the user does not unintentionally make modifications to what is expected to be "known good" reference code provided by the library author and Arduino.

So I'm not convinced that Arduino IDE 1.x saving the compiled binary inside what is intended to be somewhat of a "read-only" location was actually "right". On the other hand, doing so shouldn't cause problems like allowing a modification to the example code would because the presence of the exported binary in a sketch folder shouldn't affect the IDE in any way.

The workaround for the problem of the example sketch being in an odd temporary folder is to use **File > Save As...** to save the temporary new sketch to a persistent location on your hard drive.

>the subfolder is hard to reach

Even in the temporary folder, it is sill just as easy to reach by selecting **Sketch > Show Sketch Folder** from the Arduino IDE menus.

**Comment by kittaakos** [comment]
> Arduino IDE 1.x saving the compiled binary inside what is intended to be somewhat of a "read-only" location was actually "right".

IDE2 can prompt a dialog and guide users to save the temp sketch first when doing `Sketch` > `Export Compiled Binary`.

IDE 1.x shows this dialog when trying to save an example:

<img width="441" alt="Screen Shot 2022-09-29 at 16 04 52" src="https://user-images.githubusercontent.com/1405703/193053778-91e3748a-2ff6-4dfb-969b-f5e130ec52fb.png">

**Comment by Jens869** [comment]
I'm sorry.
Arduino 1.x places the bin file in /Documents/Arduino/name/name.bin

Arduino 2.0 in /Documents/Arduino/name/build/esp8266-something/name.bin

It's also a problem that modern operating systems hide the path, but when I **upload the file via browser** then I have to **specify the entire path.**

There it is useless to have a shortened path in Finder/Explorer.

Unless you're using the terminal/shell/cmd.exe

**Comment by per1234** [comment]
>Arduino 2.0 in /Documents/Arduino/name/build/esp8266-something/name.bin

This is intentional.

>It's also a problem that modern operating systems hide the path

Then change the operating system settings to have the right behavior. If that setting is not available, take it up with Apple.

> when I upload the file via browser then I have to I have to specify the entire path.

If that is a problem, you can move the file to a more convenient location.

**Comment by hemangjoshi37a** [comment]
where is this located in ubuntu ?
