### ISSUE TITLE
Code Completion with Light (Theia) not very good readable

### ISSUE THREAD

**Issue by holgerlembke** [arduino/arduino-ide#1543]
### Describe the problem

As shown in image:

![image](https://user-images.githubusercontent.com/2034993/194431087-c916a846-3fc5-4c5d-b090-83857687e2f4.png)

The leading "spi_" is almost not readable.

Light (Arduino) works as designed.

### To reproduce

use code completion with light (theia) color design

### Expected behavior

better readability

### Arduino IDE version

2.0.0 release

### Operating system

Windows

### Operating system version

10 (infinidash release)

### Additional context

dd

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @holgerlembke. Thanks for your report.

The decision was made to remove the "**Light (Theia)**" theme from Arduino IDE 2.x (https://github.com/arduino/arduino-ide/issues/1283) so that the available resources can be focused on  maintaining Arduino's own equivalent "**Light (Arduino)**" theme. Until that time, the "**Light (Theia)**" theme is offered "as is" and anyone experiencing problems with it is encouraged to switch to using "**Light (Arduino)**".

Please let us know if you identify any problems or areas for improvement in the supported themes.
