### ISSUE TITLE
My library doesn’t appear in Examples from Custom Library on Arduino 2.0.0 and Arduino 2.0.1

### ISSUE THREAD

**Issue by zeynepdicle** [arduino/arduino-ide#1620]
My Library is [Deneyap Kizilotesi Alici Verici](https://github.com/deneyapkart/deneyap-kizilotesi-alici-verici-arduino-library).

My library Deneyap Kizilotesi Alici Verici doesn't appear in Examples from Custom Library on Arduino 2.0.0 and Arduino 2.0.1 but this appear in Arduino 1.8.19.

How can I fix this problem?

**Comment by per1234** [comment]
Hi @zeynepdicle. The reason your examples are not shown in the menu is because they are not valid sketches.

As stated in the Arduino Sketch Specification:

https://arduino.github.io/arduino-cli/latest/sketch-specification/#primary-sketch-file

> Every sketch must contain a `.ino` file with a file name matching the sketch root folder name.

The file and folder names of your example sketches differ in case:

```text
examples/
├── KizilotesiAlici/
│   └── KizilOtesiAlici.ino
└── KizilotesiVerici/
    └── KizilOtesiVerici.ino
```

Note that the "`o`" character is lowercase in the folder names, but uppercase in the file names ("`O`").

Because Windows has a case insensitive file system, these two filenames are considered equivalent. This is why the sketch is considered valid in Arduino IDE 1.x. But we must give consideration to users of other operating systems. Linux is a case sensitive file system. Linux users will find that your examples are invalid even when using Arduino IDE 1.x, so the fact that Arduino IDE 2.x gives consistent treatment to sketches is beneficial.

**Comment by zeynepdicle** [comment]
Thank you @per1234 I could fixed
