### ISSUE TITLE
allow to open draged files 

### ISSUE THREAD

**Issue by integrated-circuit** [arduino/arduino-ide#1700]
### Describe the request

when dragging or using ctrl + O  to open the file in the sketch editor, allow it to open in the current window.

### Describe the current behavior

currently, if you open the sketch, it spawns another window to open and display the file

### Arduino IDE version

Version: 2.0.2Date: 2022-11-17T11:52:32.665Z Version CLI: 0.29.0 [76251df9]Copyright © 2022 Arduino SA

### Operating system

Linux

### Operating system version

ubuntu 22.04.1 LTS

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @integrated-circuit. Thanks for your request. The current behavior is the intentional design of Arduino IDE. Arduino IDE is a tool for developing sketches, so the sketch is the unit it works with. Each open sketch is contained in a dedicated Arduino IDE window.

This might seem unnecessary to those who are used to working with single file sketches. However, Arduino sketches [may contain multiple files](https://arduino.github.io/arduino-cli/dev/sketch-specification/#additional-code-files), all of which are [compiled as a single program](https://arduino.github.io/arduino-cli/dev/sketch-build-process/). That fact is communicated intuitively to the user by this design. If files from different sketches could be opened in the same window, it would be quite difficult to understand what exactly operations like compilation, upload, save, new tab, etc. would do.
