### ISSUE TITLE
There is no proper docs for who want to contribute first time?

### ISSUE THREAD

**Issue by shiviraj** [arduino/arduino-ide#172]
I want to contribute in this project. But I am not getting any proper docs how to start contributing in this project.  I cloned this repo in my machine. And I am not able to proceed further. Kindly prepare some docs where following details should be mentioned like:
 - dev machine setup guides
 - what dependencies are being used 
 - how to run program
 - how to write unit test
 - how to write integration testing

**Comment by rsora** [comment]
Hi @shiviraj, we are happy that you want to contribute!
Please check [here](https://github.com/arduino/arduino-ide#contributions-and-development), we have a dev environment setup guide in the [BUILDING.md](https://github.com/arduino/arduino-ide/blob/main/BUILDING.md ) file that should help you start to work on the codebase.

We will expand the documents mentioned above, adding information about testing in the following weeks.

Please note that currently for security reasons, our CI will probably fail once you push your code because it's not possible to sign Arduino IDE binaries if the CI runs on a fork. We are working to fix this anyway, I'll post a comment here once we have an update on the matter.

Happy coding!
