### ISSUE TITLE
Doesn't work with SOCKS proxy

### ISSUE THREAD

**Issue by wh201906** [arduino/arduino-ide#1769]
### Describe the problem

I have a SOCKS proxy on port `1233` and a http proxy on port `1234`. No matter which proxy type I select in Arduino IDE(`SOCKS` or `HTTP`), if I set the port to `1234`, everything works fine, if I set the port to `1233`, the network error occurs. **It seems like the Arduino always uses the http proxy regardless of the proxy type I selected.**
Plus, If I configure a http proxy in settings, it will be shown as SOCKS proxy the next time I open the Arduino IDE. But the `arduino-cli.yaml` still shows that it's a http proxy.

### To reproduce

1. Set a SOCKS proxy on port `n` and a http proxy on port `n+1`
2. In Arduino, set the SOCKS proxy on port `n`, the network error occurs (which shows the problem)
3. Set the http proxy on port `n+1`, the network works fine
4. Set the SOCKS proxy on port `n+1`, the network works fine (which is unexpected)
5. Set the http proxy on port `n`, the network error occurs

### Expected behavior

The SOCKS proxy should work.

### Arduino IDE version

Version: 2.0.3 Date: 2022-12-05T09:30:25.331Z CLI Version: 0.29.0 [76251df9]  Copyright © 2022 Arduino SA

### Operating system

Windows

### Operating system version

Windows 10

### Additional context

I have checked the proxy and I'm sure port `1233` only accepts SOCKS and `1234` only accepts http. 
Both of proxy work in other apps.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @wh201906. Thanks for your report. I was not able to reproduce it.

The instructions you provided are too vague for me to be sure I am correctly reproducing what you have done. Please provide a set of very detailed and clear instructions that I can follow for a minimal reproduction of the bug and I will continue with the investigation.

**Comment by wh201906** [comment]
Thanks for your reply. Here are the steps:
<details>
<summary>steps</summary>

1. Set a socks proxy on 127.0.0.1:1233 and a http proxy on 127.0.0.1:1234
2. Open Arduino IDE, go to preference->network
3. Set the proxy like this
![图片](https://user-images.githubusercontent.com/62299611/207525119-6de72c9b-be49-4851-9bad-85fff3a499cc.png)
4. Click OK, then the net work error occurs
![图片](https://user-images.githubusercontent.com/62299611/207525250-46e52e7d-edb2-4a35-85d0-35049ba8295b.png)
5. Set the proxy like this
![图片](https://user-images.githubusercontent.com/62299611/207525441-2a5fb585-d57e-4dd2-8a70-d839fa881333.png)
6. Click OK, the IDE shows the downloading process
![图片](https://user-images.githubusercontent.com/62299611/207525535-c9d6dcbc-fd2f-4b03-9ed9-b5915303379e.png)
7. Set the proxy like this
![图片](https://user-images.githubusercontent.com/62299611/207525760-7c6c9ddb-1028-4be6-87e7-1afb3dd13b39.png)
8. Click OK, the IDE shows the downloading process
![图片](https://user-images.githubusercontent.com/62299611/207525929-333ade8f-721f-4486-b46f-619fddd0e032.png)
**This is weird because port 1234 only accepts http proxy**
9. Set the proxy like this
![图片](https://user-images.githubusercontent.com/62299611/207526519-ac4d1b4f-2211-4166-b864-0d93e138fc21.png)
10. Click OK, then the net work error occurs
![图片](https://user-images.githubusercontent.com/62299611/207526562-5ff0a1c6-a265-499e-9686-7068265c9ed6.png)

</details>

# Additional information
When changing the proxy in the Arduino IDE, I can see the configuration is applied to the `arduino-cli.yaml`
![图片](https://user-images.githubusercontent.com/62299611/207527149-272fb7ac-38b9-48e0-b3fc-36a5ee745267.png)![图片](https://user-images.githubusercontent.com/62299611/207527281-21221a66-7dc9-4cac-89af-8c019df6ca96.png)![图片](https://user-images.githubusercontent.com/62299611/207527634-5ddab1d0-fa14-44f6-b76f-7753a359018a.png)
I guess it's something wrong in the Arduino-cli?
Plus, when dumping the config in arduino-cli, I can't see the network config.
![图片](https://user-images.githubusercontent.com/62299611/207528181-9ebfc364-00c4-41b9-9ff3-4e0bbac3d705.png)
Please tell me if you need more information.

**Comment by per1234** [comment]
Thanks so much for that additional information @wh201906. That was very helpful. I was able to reproduce the bugs you reported here and track down the cause of the primary bug:

## SOCKS Proxy Doesn't Work

> 4. Click OK, then the net work error occurs

> 8. Click OK, the IDE shows the downloading process
>[...]
>This is weird because port 1234 only accepts http proxy

> My proxy software shows the Arduino IDE is still using http proxy even if I just set a socks proxy

> I guess it's something wrong in the Arduino-cli?

### Explanation

It is actually a bug in Arduino IDE that is causing all these symptoms. The problem is it uses the `socks` scheme in the URL when it sets the Arduino CLI proxy configuration via the `network.proxy` key of `arduino-cli.yaml`. The `net/http` Go package used by Arduino CLI requires the scheme to instead be `socks5`:

https://pkg.go.dev/net/http#Transport

I was not able to track down the code responsible for the behavior, but it seems that HTTP is used as a fallback when the scheme in the proxy URL is not recognized. This is why you found the HTTP proxy works even when you set the radio button to "**SOCKS**" in the Arduino IDE preferences and it sets the `network.proxy` key to a `socks://` URL.

### Workaround

1. Open the following file in a text editor (I realize you already know where it is, but I'll provide comprehensive instructions for the benefit of any other users who might be affected):
   - If you are using **Windows**:
     ```text
     C:\Users\<username>\.arduinoIDE\
     ```
   - If you are using **Linux**:
     ```text
     ~/.arduinoIDE/
     ```
   - If you are using **macOS**:
     ```text
     ~/.arduinoIDE/
     ```
1. Change the `socks://` part of the URL in the `network.proxy` key to `socks5://`
   For example, if the file contained this:
   ```yaml
   network:
     proxy: socks://127.0.0.1:1233
   ```
   It should be changed to this:
   ```yaml
   network:
     proxy: socks5://127.0.0.1:1233
   ```
1. Save the file.
1. If Arduino IDE is running, select **File > Quit** from the menus to close all windows.
1. Start Arduino IDE.

## Proxy Configuration Set by Arduino IDE not Shown in `arduino-cli config dump` Output

>After setting the proxy in Arduino IDE, I can't see the network config when dumping the config in arduino-cli.

Arduino CLI recognizes `arduino-cli.yaml` configuration files in several locations:

https://arduino.github.io/arduino-cli/latest/configuration/#locations

The dedicated `~/.arduinoIDE/arduino-cli.yaml` file used by Arduino IDE is not in one of these locations (unless you happen to be running the `arduino-cli` command from that folder). So if you run `arduino-cli config dump` you will get the effective configuration of Arduino CLI (either the defaults, or taken from an `arduino-cli.yaml` file if it exists in one of the recognized locations.

You can set the location of the file via the [--config-file](https://arduino.github.io/arduino-cli/latest/commands/arduino-cli/#options) command line flag, so if you run this command you would see the Arduino IDE configuration in the output:

```text
arduino-cli config dump --config-file $Env:HOMEDRIVE$Env:HOMEPATH/.arduinoIDE/arduino-cli.yaml
```

## "Preferences" Dialog Shows Incorrect Proxy Type

> Open Arduino IDE, go to Preferences->Network, the proxy type switches from http to socks

I am able to reproduce this. I think it will be more effective and efficient to dedicate this issue exclusively to the incorrect `socks` URL scheme used when configuring Arduino CLI for a SOCKS proxy, so I have created a separate issue to track the bug with the incorrect radio button selection in the "**Preferences**" dialog: https://github.com/arduino/arduino-ide/issues/1775

**Comment by wh201906** [comment]
Thanks for handling these bugs!

**Comment by wh201906** [comment]
> The `net/http` Go package used by Arduino CLI requires the scheme to instead be `socks5`

@per1234 Hi. Can I make a PR to make a fix for it?

**Comment by per1234** [comment]
Yes, a PR would be welcome!
