### ISSUE TITLE
Entire "Tools > Port" menu disabled and no ports discovered when using back USB port

### ISSUE THREAD

**Issue by EmmanuelMess** [arduino/arduino-ide#1834]
### Describe the problem

No ports discovered:
![image](https://user-images.githubusercontent.com/10991116/214640767-80d3b098-b5c5-4677-a31a-605dc98df689.png)

### To reproduce

Open Arduino IDE, connect arduino uno board to usb board.

### Expected behavior

It should detect my port and board.

### Arduino IDE version

Version: 2.0.4-nightly-20230125 Date: 2023-01-25T03:03:17.544Z CLI Version: 0.29.0  Copyright © 2023 Arduino SA

### Operating system

Linux

### Operating system version

Ubuntu 20.04

### Additional context

* Similar to #605 (closed as fixed).
* Could not make it detect the port even restaring the computer.
* Connecting the arduino to front port it detects it
* Back port works for connecting phone and transfering files.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @EmmanuelMess. Thanks for your report.

In order to gather more information that might help us to troubleshoot your problem, I'm going to ask you to run [the `lsusb` command](https://www.linux.com/training-tutorials/find-usb-device-details-linuxunix-using-lsusb-command/) from the command line and share the output.

1. Open [a terminal](https://ubuntu.com/tutorials/command-line-for-beginners).
1. If it is not already connect the USB cable of your Arduino board to your computer.
1. Type `lsusb`
1. Press <kbd>Enter</kbd>
1. Click and drag the mouse to select all the output in the terminal window.
1. Press **<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>**.
   This will [copy](https://lifehacker.com/how-to-copy-cut-and-paste-for-beginners-5801525) the selected text to the clipboard.
1. Paste (**<kbd>Ctrl</kbd>+<kbd>V</kbd>**) the output in a reply to this GitHub issue thread.

**Comment by per1234** [comment]
Does your "Uno" have the WCH CH340 USB chip?

![image](https://user-images.githubusercontent.com/8572152/214851176-9577139a-16c7-4c48-9cb4-2df0c8c15855.png)

If so, I can see the system recognized it when "connected on the back":

>```text
>Bus 005 Device 012: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter
>```

But not when "connected on the front".

This means the problem with the port is at a system level and not anything related to Arduino IDE. So I'll close the issue here. But you are welcome to request assistance with the system problem over on the Arduino Forum:

https://forum.arduino.cc/

I'll sure we'll be able to help you over there

**Comment by EmmanuelMess** [comment]
But connected to the front the arduino ide detects it, but not when connected to the back. So when the system detects it, it doesn't work? That sounds like an ide issue.

**Comment by EmmanuelMess** [comment]
Forum link: https://forum.arduino.cc/t/usb-port-not-detected-with-arduino-ide-2/1092204
