### ISSUE TITLE
Enter Key in editor goes to correct indented position, then moves. 

### ISSUE THREAD

**Issue by iplayfast** [arduino/arduino-ide#1855]
### Describe the problem

...
   if (avail) {

pushing return after the { move the cursor to indent just after the if which looks acceptable to me. It then after 1/4 of a second moves to the beginning of the line. (very weird). 
It seems to happen if there are spaces after the {, and instead of removing trailing spaces and then moving the cursor, it's moving the cursor and then removing the spaces, including the ones before the cursor.

### To reproduce

Type the following code

if (this)
   if (that) {<space><space><space)

reposition the cursor to after the { and push enter.

### Expected behavior

remove trailing spaces,add a newline and indent properly.

### Arduino IDE version

2.03

### Operating system

Linux

### Operating system version

Mint 23

### Additional context

I've found the editor to be frustrating to use.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @iplayfast. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/437.

There are instructions for the workaround to the bug here:

https://github.com/arduino/arduino-ide/issues/437#user-content-workaround

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
