### ISSUE TITLE
Language server makes incorrect calculation of variable value

### ISSUE THREAD

**Issue by rdaek** [arduino/arduino-ide#1856]
### Describe the problem

I have a variable/MACRO, which value is presented as multiplication of numbers and there is wrongly calculated value by compiler.

Example:

```cpp
#define MAX_PULSE_LEN = (unsigned long )(15*60*1000);
unsigned long MAX_PULSE_LEN =(15*60*1000);
```

shows 4294949792 instead of 900000:

![Snímek obrazovky (21)](https://user-images.githubusercontent.com/20031239/216318282-20a10614-1951-427f-957f-35c0929dd9b9.png)

### To reproduce

Just make variable/macro with higher value at init

### Expected behavior

Should have good value

### Arduino IDE version

2.0.2

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @rdaek. If you make your sketch display the value via a `Serial.print` call, you will see the same value as the language server calculated.

The reason is explained here:

https://www.arduino.cc/reference/en/language/variables/constants/integerconstants/#_description

> Integer constants are numbers that are used directly in a sketch, like 123. By default, these numbers are treated as [`int`](https://www.arduino.cc/reference/en/language/variables/data-types/int)

https://www.arduino.cc/reference/en/language/variables/data-types/int/#_notes_and_warnings

> When signed variables are made to exceed their maximum or minimum capacity they overflow.

> A typical symptom of an overflow is the variable "rolling over" from its maximum capacity to its minimum or vice versa

> On the Arduino Uno (and other ATmega based boards) an `int` stores a 16-bit (2-byte) value. This yields a range of -32,768 to 32,767 (minimum value of -2^15 and a maximum value of (2^15) - 1).

So your code actually produces two overflows:

- 16-bit overflow due to the integer literal exceeding the maximum of 32767
- signed 32-bit overflow (or you might say "underflow") due to exceeding the unsigned long variable minimum of 0

I think this sketch will make things more clear:

```cpp
void setup() {
  Serial.begin(9600);
  while (!Serial) {}

  Serial.print("(unsigned long)(15 * 60 * 1000) = ");
  Serial.println((unsigned long)(15 * 60 * 1000));

  Serial.print("15 * 60 * 1000 = ");
  Serial.println(15 * 60 * 1000); // 16-bit overflow of integer literal (on architectures w/ 16 bit int)

  Serial.print("(unsigned long)(-17504) = ");
  Serial.println((unsigned long)(-17504)); // 32-bit overflow of unsigned long variable

  Serial.print("15 * 60 * 1000UL = ");
  Serial.println(15 * 60 * 1000UL); // Use UL suffix to specify unsigned long type for integer literals
}
void loop() {}
```

As you can see, if you want your integer literals to be treated as `unsigned long` type instead of the default `int`, you must use the `UL` suffix. It is not sufficient for the defined variable type to be `unsigned long`.

If you have any questions about this, you are welcome to ask on the Arduino Forum:

https://forum.arduino.cc/c/using-arduino/programming-questions/20
