### ISSUE TITLE
Release 2.0.4 is missing macOS ARM version

### ISSUE THREAD

**Issue by martinvandiemen** [arduino/arduino-ide#1929]
### Describe the problem

The latest release (2.0.4) is missing macOS ARM version. Version 2.0.3 has an ARM version.

### To reproduce

https://github.com/arduino/arduino-ide/releases/tag/2.0.4

### Expected behavior

A release for macOS ARM.

### Arduino IDE version

2.0.4

### Operating system

macOS

### Operating system version

13.2.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Thanks for the report @martinvandiemen. We added it to [the arduino.cc "**Software**" page](https://www.arduino.cc/en/software) and also set things up for the auto-update at the time of the release because that is where most people get Arduino IDE. However, it is useful to have them on the GitHub release page so I've now added them there as well.
