### ISSUE TITLE
Code formatting issue with the "Format Code" feature of Arduino IDE 2.0.

### ISSUE THREAD

**Issue by MicSG-dev** [arduino/arduino-ide#2095]
### Describe the problem

When using the code formatting feature of Arduino IDE 2.0 (Ctrl + T shortcut), I noticed an unexpected behavior when the code contains a "while" statement with a line that consists of only a semicolon. The formatter moves the semicolon to the next line, resulting in an undesired outcome.
Example:
while (1);
is incorrectly formatted as
while (1)
 ;

### To reproduce

1. Open Arduino IDE 2.0.
2. Create a new sketch or open an existing one.
3. Insert the following code on a single line: "while (1);"
4. Use the Ctrl + T shortcut to format the code.

### Expected behavior

After following the steps above, I would expect the semicolon to remain on the same line, aligned with the code `while (1);`.

### Arduino IDE version

2.1.0

### Operating system

Windows

### Operating system version

Windows 11 Home 22H2 x64 (OS Build 22621.1778)

### Additional context

When using the code formatting feature, it is important that the resulting formatting is correct and does not alter the code's behavior. However, when using the Ctrl + T shortcut with the mentioned code, the semicolon is moved to the next line, which can negatively impact code readability and potentially introduce errors.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @MicSG-dev. The formatting produced by the Arduino IDE "Auto Format" feature is provided by the [**ClangFormat**](https://clang.llvm.org/docs/ClangFormat.html) formatter. Arduino does not maintain that tool so reports of formatting that is other than you hoped for are off topic here.

Note that the code produced by the formatter is not incorrect, but rather simply doesn't happen to match your personal code style preferences.

It is possible to customize the behavior of the Arduino IDE 2.x Auto Format feature, as documented here:

https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-customize-auto-formatter

You might find that one of the many ClangFormat configuration options will provide the formatting you desire.

My suggestion is to use this equivalent code instead, which will remain on a single line:

```cpp
while(1) {}
```

Since you expressed concern about the potential for introduction of errors, I'll mention that the equivalent code I suggest follows what some consider best practices (e.g., [JSF AV](https://www.stroustrup.com/C++.html#:~:text=JSF%2B%2B%3A%20The%20JSF%20air%20vehicle%20C%2B%2B%20coding%20standards) Rule 59) of always using braces on a flow control block.
