### ISSUE TITLE
Arduino IDE 2.1.0: blank white IDE

### ISSUE THREAD

**Issue by rs0xFFFF** [arduino/arduino-ide#2099]
### Describe the problem

It happens very often that the IDE doesn't load anything when you open it and you only see a white surface. Furthermore, it takes a long time (maybe 30 sec) until a source code becomes visible when it works.

### To reproduce

n.a.

### Expected behavior

n.a.

### Arduino IDE version

2.1.0

### Operating system

Windows

### Operating system version

Win7

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @rs0xFFFF. I am closing this because we don't officially support using Arduino IDE 2.x with the long retired Windows 7.

You are welcome to request assistance with the problem on Arduino Forum:

https://forum.arduino.cc/c/software/ide-2-x/93

I will suggest the workaround of using Arduino IDE 1.8.19 until such time as you are able to update to a modern version of Windows. The Arduino IDE 1.8.19 download links are listed here:

https://www.arduino.cc/en/software#legacy-ide-18x
