### ISSUE TITLE
The M1 macOS build artifact should follow the Arduino asset naming convention

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#2117]
### Describe the problem

The following artifacts do not follow the asset naming convention.

 - [arduino-ide_2.1.0_macOS_arm64.dmg](https://github.com/arduino/arduino-ide/releases/download/2.1.0/arduino-ide_2.1.0_macOS_arm64.dmg)
 - [arduino-ide_2.1.0_macOS_arm64.zip](https://github.com/arduino/arduino-ide/releases/download/2.1.0/arduino-ide_2.1.0_macOS_arm64.zip)

should be `arduino-ide_2.1.0_macOS_ARM64.dmg` and `arduino-ide_2.1.0_macOS_ARM64.zip`

### To reproduce

The IDE2 artifact naming convention follows the convention used by the Arduino CLI, LS, FW Uploader, etc.

### Expected behavior

The IDE2 assets follow the Arduino asset naming convention.

### Arduino IDE version

2.1

### Operating system

macOS

### Operating system version

13.4.1

### Additional context

The M1 build is manual.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Unfortunately this won't be possible because the use of the exact `arm64` architecture identifier in the artifact filename is hardcoded into electron-updater:

https://github.com/electron-userland/electron-builder/blob/7704be02a076ec51a5bf118f59c0d47927b5c85f/packages/electron-updater/src/MacUpdater.ts#L67

```typescript
    const isArm64 = (file: ResolvedUpdateFileInfo) => file.url.pathname.includes("arm64") || file.info.url?.includes("arm64")
    if (isArm64Mac && files.some(isArm64)) {
      files = files.filter(file => isArm64Mac === isArm64(file))
    } else {
      files = files.filter(file => !isArm64(file))
    }
```

In fact we had the `ARM64` identifier originally: https://github.com/arduino/arduino-ide/commit/f6275f9f62e66df091ac6e12bfc78d56f36c2380 and it had to be changed to the current `arm64` identifier because it caused the incorrect version of Arduino IDE to be installed on update. There is a more detailed explanation in the PR for that bug fix: https://github.com/arduino/arduino-ide/pull/1919
