### ISSUE TITLE
New Arduino IDE doesn't remember port making it impossible to unbrick Pro Micro using it

### ISSUE THREAD

**Issue by xCuri0** [arduino/arduino-ide#2136]
I tried following this guide https://learn.sparkfun.com/tutorials/pro-micro--fio-v3-hookup-guide/troubleshooting-and-faq#ts-revive using the new Arduino IDE and it was impossible because pressing CTRL + U didn't work with no port and selecting the port and pressing CTRL+U takes too long. I was only able to do it using the old Arduino IDE and resetting after I press CTRL + U

**Comment by per1234** [comment]
Hi @xCuri0 . Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/2089.

That bug has already been fixed:

- https://github.com/arduino/arduino-cli/pull/2202
- https://github.com/arduino/arduino-ide/pull/2090

I guess you are still experiencing the problem because the fix was made after the latest release. Please try the latest nightly build of Arduino IDE. The download links are listed here:

https://www.arduino.cc/en/software#nightly-builds
