### ISSUE TITLE
Include Plugins Tab in Arduino IDE

### ISSUE THREAD

**Issue by MicSG-dev** [arduino/arduino-ide#2162]
### Describe the request

Just as in Visual Studio Code there is the [Extension Marketplace](https://code.visualstudio.com/docs/editor/extension-marketplace) functionality, in Arduino IDE there could be such a function to facilitate the installation of plugins, such as:

[Arduino ESP8266 LittleFS Filesystem Uploader](https://github.com/earlephilhower/arduino-esp8266littlefs-plugin) by @earlephilhower;
[Arduino ESP32 LittleFS filesystem uploader](https://github.com/lorol/arduino-esp32littlefs-plugin) by @lorol;
[Arduino Pico LittleFS Filesystem Uploader](https://github.com/earlephilhower/arduino-pico-littlefs-plugin) by @earlephilhower;
[Arduino ESP32 filesystem uploader (SPIFFS)](https://github.com/me-no-dev/arduino-esp32fs-plugin) by @me-no-dev;
[Arduino ESP8266/ESP32 Exception Stack Trace Decoder](https://github.com/me-no-dev/EspExceptionDecoder) by @me-no-dev;
between others.

Preview of the Extension Marketplace feature in Visual Studio Code:
![Code_GksU9SW8Dw](https://github.com/arduino/arduino-ide/assets/71986598/a0b9a172-2e6a-4a35-b4c7-b244c441d29d)

### Describe the current behavior

The Arduino IDE 2.0 does not support installing plugins, nor does it have a central location for installing plugins, as in Visual Studio Code.

### Arduino IDE version

2.1.1

### Operating system

Windows

### Operating system version

Windows 11 Home 22H2 x64 (OS Build 22621.2070)

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @MicSG-dev. Thanks for your suggestion.

> installation of plugins, such as:
>
>[Arduino ESP8266 LittleFS Filesystem Uploader](https://github.com/earlephilhower/arduino-esp8266littlefs-plugin) by @earlephilhower;
[Arduino ESP32 LittleFS filesystem uploader](https://github.com/lorol/arduino-esp32littlefs-plugin) by @lorol;
[Arduino Pico LittleFS Filesystem Uploader](https://github.com/earlephilhower/arduino-pico-littlefs-plugin) by @earlephilhower;
[Arduino ESP32 filesystem uploader (SPIFFS)](https://github.com/me-no-dev/arduino-esp32fs-plugin) by @me-no-dev;
[Arduino ESP8266/ESP32 Exception Stack Trace Decoder](https://github.com/me-no-dev/EspExceptionDecoder) by @me-no-dev;

Those are Arduino IDE 1.x "plugins". They are fundamentally incompatible with Arduino IDE 1.x and so it will never be possible to install them.

>The Arduino IDE 2.0 does not support installing plugins

The [**Eclipse Theia** framework](https://theia-ide.org/) Arduino IDE is built on provides support for extending the capability of Arduino IDE via VS Code extensions. Installation of these extensions is already supported and we even provide instructions for doing so specific to theme extensions:

https://github.com/arduino/arduino-ide/blob/main/docs/advanced-usage.md#3rd-party-themes

In order to create extensions equivalent to the established Arduino IDE 1.x plugins, access to the Arduino framework data is needed in addition to the basic extension support. We are tracking that task here: https://github.com/arduino/arduino-ide/issues/58. That was recently implemented:

https://github.com/arduino/arduino-ide/pull/2110

And the first Arduino IDE 1.x plugin replacement created:

https://github.com/dankeboy36/esp-exception-decoder

So there is indeed such support at a technical level. The remaining work to resolve https://github.com/arduino/arduino-ide/issues/58 is to produce documentation of the Arduino-specific parts of the extension system.

---

That leaves your primary request; the "Plugins Tab". This was requested previously and declined: https://github.com/arduino/arduino-ide/issues/207. As explained there, although we do provide a framework for extending the capabilities of Arduino IDE 2.x, this is something intended only for advanced users. Those users can manage their custom extensions directly via the file system, as is already supported.
