### ISSUE TITLE
compile without warning / pass Assignment to Boolean (Aruino IDE  2.1.0  &  2.2.1 )

### ISSUE THREAD

**Issue by caslor** [arduino/arduino-ide#2219]
### Describe the problem

when i use FreeRTOS   in a Task   if  i use an  " if "  statement  to compare a Boolean  and by mistake  place "="  instead of  "==" , then it compiles it  without a warning  and  pass the  value to the Boolean 

### To reproduce

```cpp
/*
Free RTOS  Arduino IDE 2.1.0 & 2.2.1    Esp32 
No warning when place "="  instead "=="  to if statement and passing the value to the Boolean 
*/

bool Moving = false;
TaskHandle_t Task_1;
TaskHandle_t Task_2;

void setup() {
  Serial.begin(115200);
  xTaskCreate(
    Task1,     // Task function.
    "Task 1",  // name of task.
    1024,      // Stack size of task
    NULL,      // parameter of the task
    3,         // priority of the task
    &Task_1    // Task handle to keep track of created task
  );           // pin task to core 0
  xTaskCreate(
    Task2,     // Task function.
    "Task 2",  // name of task.
    1024,      // Stack size of task
    NULL,      // parameter of the task
    3,         // priority of the task
    &Task_2    // Task handle to keep track of created task
  );           // pin task to core 0
}

void Task1(void *pvParameters) {  
  for (;;) {
    Moving = false;
    Serial.print("  Boolean Moving: ");
    Serial.println(Moving);
    //vTaskDelay(10 / portTICK_PERIOD_MS);
  }
}

void Task2(void *pvParameters) { 
  for (;;) {
    if (Moving = true) {  //  If by mistake place =  instead of ==   , no warning in compiler and changes the boolean 
    }
    Serial.print("  Boolean Moving: ");
    Serial.println(Moving);
    //vTaskDelay(10 / portTICK_PERIOD_MS);
  }
}

void loop() {}
```

### Expected behavior

To appear  compile warning  that   Assignment  "="  not followed by  ";"  or  if statement has  wrong type of comparison "="

### Arduino IDE version

2.1.0 , 2.2.1

### Operating system

Linux

### Operating system version

Linux Mint  20.04

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @caslor. Although they are displayed in the Arduino IDE "Output" panel, compiler warning messages do not originate from the Arduino IDE codebase. As you might guess, they come from the compiler.

Arduino IDE is not a compiler and Arduino does not develop or maintain compilers. Arduino IDE only invokes standard C++ compilers (typically [**GCC**](https://gcc.gnu.org/)) according to the arbitrary configurations defined in the [platform](https://arduino.github.io/arduino-cli/latest/platform-specification/) of the board that is selected in Arduino IDE at the time of the compilation. So reports about the configuration or behavior of the compilation commands are off topic for this repository.

> it compiles it without a warning

I guess you don't have compiler warnings fully enabled in your Arduino IDE preferences. If you had the Arduino IDE "**Compiler warnings**" preference set to "**More**" or "**All**", you would see this does generate a compiler error (even if not the one you hoped for):

```text
C:\Users\per\AppData\Local\Temp\.arduinoIDE-unsaved202386-17996-vrxpmd.1oii\sketch_sep6a\sketch_sep6a.ino: In function 'void Task2(void*)':
C:\Users\per\AppData\Local\Temp\.arduinoIDE-unsaved202386-17996-vrxpmd.1oii\sketch_sep6a\sketch_sep6a.ino:41:16: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
     if (Moving = true) {  //  If by mistake place =  instead of ==   , no warning in compiler and changes the boolean
         ~~~~~~~^~~~~~
cc1plus.exe: some warnings being treated as errors

exit status 1

Compilation error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
```

The reason it is an error is because the ESP32 boards platform developers have configured the compilation commands to fail on warnings (via the [`-Werror=all`](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Werror) flag) in order to encourage developers to produce high quality code.
