### ISSUE TITLE
Add fuse bits override for AVR MCUs

### ISSUE THREAD

**Issue by freeman401** [arduino/arduino-ide#2295]
### Describe the request

Sometimes existing board settings are not enough when using bare MCU and programmer. And editing 'boards.txt' is really inconvenient.
Would it be possible to add some kind of a custom preprocessor directive to explicitly set fuse bits in code?
For example:
`#setfusel 0x12`
`#setfuseh 0x34`
`#setfusee 0x56`
Or even to modify them like so:
`#setfusel BOARDFUSEL | 0x01`
`#setfuseh BOARDFUSEH & 0xFA`

If it is not feasible or really tricky to implement, then perhaps one of these ideas might work:
- Add support for a local 'boards.txt' file in the project folder that will extend and/or override the main one.
- Add a button to the tools menu or board manager that opens 'boards.txt' in the editor.
- ~~_Add official support for every single bare AVR MCU and make a fuse bit configuration utility_~~ 😁

### Describe the current behavior

Possible fuse bits configurations are limited by the board author.

### Arduino IDE version

2.2.2-nightly-20231127

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @freeman401. Thanks for your suggestion. Changing fuse bits from the sketch program is not possible at a fundamental technical level so this can not be implemented.

Even if you find editing `boards.txt` to be inconvenient, it is an inconvenience that only needs to be suffered once, and that only by a small number of very advanced users. If any significant number of users has the need for such a configuration, one of them is sure to create a custom boards platform so that the rest of the community can avoid the need to make the customizations manually. So I don't think the inconvenience is something to be concerned about.

If you are doing it frequently then this indicates you are taking an inefficient approach to accomplishing your goal. If so, we would be happy to suggest an improved approach if you ask over on Arduino Forum:

https://forum.arduino.cc/

>Add support for a local 'boards.txt' file in the project folder that will extend and/or override the main one.

This was requested previously and declined by the developers as unnecessary: https://github.com/arduino/arduino-cli/issues/1684
