### ISSUE TITLE
Define and use custom code snippet like in vscode

### ISSUE THREAD

**Issue by ascodeasice** [arduino/arduino-ide#2320]
### Describe the request

Code snippet is a feature in vscode, that allows user to create template code by typing defined texts, ex: `#endregion` becomes `#pragma endregion`.

The request is allowing user to define their own snippet in a JSON file, such as `lcdInit` creates three lines of code initializing LCD (just like vscode).

So, I hope I can:

1. define snippets in a file
2. get suggested when typing, and select them, then defined code will appear

This feature would be useful when writing some repeated code with certain template

### Describe the current behavior

I couldn't find such setting in the command palette or setting, but in vscode, it can be found in command palette, so I think this feature doesn't exist yet.

### Arduino IDE version

2.2.2-nightly-20231228

### Operating system

Windows

### Operating system version

Windows 11 22H2

### Additional context

[Snippets in Visual Studio Code (document)](https://code.visualstudio.com/docs/editor/userdefinedsnippets)

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @ascodeasice. Thanks for your suggestion. This feature has already been requested for addition to the [**Eclipse Theia** IDE framework](https://theia-ide.org/) upon which Arduino IDE is built: https://github.com/eclipse-theia/theia/issues/3686

Since it is already tracked in the Theia project, and since Arduino IDE will inherit user snippets support as a matter of course once it has been implemented in Theia, I will close this issue as superfluous.
