### ISSUE TITLE
User-I/F 

### ISSUE THREAD

**Issue by theOldieone** [arduino/arduino-ide#2333]
### Describe the problem

to the ARDUINO IDE 2.2.1, which I have been using for a few days:
1. There is a spelling mistake (see attachment) 
2. There is no longer an icon for "Save file"
3. On 'Mouseover' on the icons on the left below each other there are no context explanations (like the ones in the top bar (Check..).

![Spelling](https://github.com/arduino/arduino-ide/assets/156835994/a8fc8d13-0ecb-457f-9ca1-6a24ba9859c4)
To say it clear: The topics described are mainly improvents. 
Thanks in advance
Herbert

### To reproduce

Simply use the user- I/F

### Expected behavior

see 'Describe the problem'

### Arduino IDE version

2.2.1

### Operating system

Windows

### Operating system version

22H2

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @theOldieone. Thanks for your report.

First of all, in the future please create a separate issue for each distinct subject. This type of issue where multiple distinct and unrelated reports are mashed together in a single issue is very difficult for us to manage and track. This makes it more likely for us to lose track of one of the reported items and therefore makes it less likely to be resolved.

> There is a spelling mistake (see attachment)

Nice catch! Please submit a correction to the Arduino IDE 2.x Transifex project:

https://explore.transifex.com/arduino-1/ide2/

There is more information about contributing to the Arduino IDE translations here:

https://github.com/arduino/arduino-ide/blob/main/docs/contributor-guide/translation.md#translator-guide

Your contributions will be very welcome!

> There is no longer an icon for "Save file"

This was intentional. Please use one of the alternative interfaces for saving your sketch.

>On 'Mouseover' on the icons on the left below each other there are no context explanations (like the ones in the top bar (Check..).

I was not able to understand what you mean by this. Please open a dedicated issue and provide a much more detailed description.
