### ISSUE TITLE
Please add Github Copilot

### ISSUE THREAD

**Issue by AndKe** [arduino/arduino-ide#2358]
### Describe the request

A subject says, please add support for github copilot.
VScode, PyCharm and others already have it, i would be very nice to Arduino too.

### Describe the current behavior

-

### Arduino IDE version

2.3.0

### Operating system

Linux

### Operating system version

Ubuntu 23.10

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Yeah, this is the sort of thing that should be done through extensions rather than built into the stock Arduino IDE installation.

Unfortunately, although adding capabilities to Arduino IDE by installing VS Code extensions is possible in general, the GitHub Copilot extension has some distinctive requirements that apparently are not currently supported by the [**Eclipse Theia** IDE framework](https://theia-ide.org/) on which Arduino IDE is built.

Since the support for GitHub Copilot will not be implemented in the codebase of this repository, I'll close this as declined.

For details on @AndKe and my findings in regards to the extension, or to discuss the subject further, see this Arduino Forum topic:

https://forum.arduino.cc/t/add-github-copilot-to-arduino-ide/1254539
