### ISSUE TITLE
Please add option to disable internet access and automatic update of any file

### ISSUE THREAD

**Issue by rtek1000** [arduino/arduino-ide#2401]
### Describe the request

Please add option to disable internet access and automatic update of any file.

I don't want the IDE to access the internet every time I open it. I just want you to do some searching for updates if I'm interested.

### Describe the current behavior

One of the things that irritates me most about Arduino IDEs is the IDE initialization. I always access the internet and I have no way to disable it. If I disable the network, it still generates notification.

### Arduino IDE version

2.3.2

### Operating system

Linux

### Operating system version

Xubuntu "Ubuntu 22.04.3 LTS"

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @rtek1000. The IDE's check for updates to the installed boards platforms, libraries, and the IDE application itself can be disabled via the Arduino IDE [advanced settings](https://github.com/arduino/arduino-ide/blob/main/docs/advanced-usage.md#advanced-settings). I'll provide instructions for doing that:

1. Press the <kbd>**Ctrl**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> keyboard shortcut (<kbd>**Command**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> for macOS users) to open the "Command Palette".
   A menu will appear on the editor toolbar:
   ![Command Palette](https://github.com/arduino/arduino-ide/assets/8572152/a117c17d-82f8-417d-addd-221d524b04ea)
1. Select the "**Preferences: Open Settings (UI)**" command from the menu.
   **ⓘ** You can scroll down through the list of commands to find it or type the name in the field.
   A "**Preferences**" tab will open in the Arduino IDE main panel.
1. Type `arduino.checkForUpdates` in the "**Search Settings**" field of the "**Preferences**" tab.
1. Uncheck the box under the "**Arduino: Check For Updates**" setting.
1. Close the **Preferences** tab by clicking its **X** icon.

## Checking for Boards Platform and Library Updates

You can manually trigger checks for available updates to the installed boards platforms and libraries by the following procedure:

1. Press the <kbd>**Ctrl**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> keyboard shortcut (<kbd>**Command**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> for macOS users) to open the "Command Palette".
   A menu will appear on the editor toolbar.
1. Select the "**Arduino: Update Indexes**" command from the menu.
   **ⓘ** You can scroll down through the list of commands to find it or type the name in the field.
1. Wait for the index downloads to finish.
   ❗ If you have enabled the "**Workbench: Silent Notifications**" advanced setting, you will need to open the IDE's "notification center" in order to see the notification that shows the index download progress.
1. Select **Tools > Board > Boards Manager...**" from the Arduino IDE menus.
   The "**BOARDS MANAGER**" view will open in the IDE's left panel.
1. Select "**Updatable**" from the "**Type**" menu.
1. If any updatable platforms are listed, you can click the "**UPDATE**" button to update them.
1. Select **Tools > Manage Libraries...**" from the Arduino IDE menus.
   The "**LIBRARY MANAGER**" view will open in the IDE's left panel.
1. Select "**Updatable**" from the "**Type**" menu.
1. If any updatable libraries are listed, you can click the "**UPDATE**" button to update them.

## Checking for IDE Updates

You can manually trigger checks for available updates to the Arduino IDE application by selecting **Help > Check for Arduino IDE Updates** from the Arduino IDE menus.
