### ISSUE TITLE
Unable to make Appimage IDE 2.3.2 executable

### ISSUE THREAD

**Issue by sirandrewthomson** [arduino/arduino-ide#2407]
### Describe the problem

I just downloaded Arduino ide 2.3.2 linux 64 to a new Raspberry Pi 5. Documentation says go to permissions to made Appimage executable. There is no box to check. How do I make the Appimage executable?

### To reproduce

Download Arduino IDE 2.3.2 linux64 on RPi 5, right click to go to permissions and there is no Box to make the Appimage executable

### Expected behavior

Nothing

### Arduino IDE version

2.3.2

### Operating system

Linux

### Operating system version

Raspberry Pi OS with desktop and recommended software · Release date: March 15th 2024 · System: 64-bit · Kernel version: 6.6 · Debian version: 12 (bookworm)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @sirandrewthomson. The [Linux installation instructions](https://docs.arduino.cc/software/ide-v2/tutorials/getting-started/ide-v2-downloading-and-installing/#linux) are somewhat specific to the user interface of the GNOME [**Files**](https://apps.gnome.org/en/Nautilus/) file manager. The procedure for making the Appimage file executable will be a bit different when using an different file manager, as is the case with a default Raspberry Pi OS installation. When using the Raspberry Pi OS file manager, there is an "**Execute**" menu instead of a checkbox.

But beyond you learning to use the user interface of your file manager, there is a more significant problem: which is that Arduino does not currently provide official builds of Arduino IDE 2.x for the Linux ARM architecture of your Raspberry Pi (https://github.com/arduino/arduino-ide/issues/107).

Arduino does provide Linux ARM builds of Arduino IDE 1.x. The download link is listed here:

https://www.arduino.cc/en/software#legacy-ide-18x
