### ISSUE TITLE
Move the .ino .h .c tabs from the top of the screen

### ISSUE THREAD

**Issue by el-samiyel** [arduino/arduino-ide#2425]
### Describe the request

With the real estate we have on the screen, it would be better and much faster to have a list of project files to the left hand side of the screen. Perhaps an icon under the search icon to the far left could be used to list all of the project files in alphabetical order. You can then click through these to edit the code instead of click through the tabs at the top that sometime go off the screen...
![Screenshot 2024-04-29 135536](https://github.com/arduino/arduino-ide/assets/20979725/53ab7b6e-a39a-49a4-9ec2-9cab4b34ed99)

### Describe the current behavior

All .ino .h .c files are in selectable tabs at the top of the screen

### Arduino IDE version

2.3.2

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @el-samiyel. Thanks for taking the time to submit a suggestion. I am happy to say that the requested functionality is already available. Click the **●●●** icon on the right side of the editor toolbar. A menu will open that contains a list of all tabs. You can click any of these items in the menu to select that tab in the editor.

> Perhaps an icon under the search icon to the far left could be used to list all of the project files in alphabetical order.

There is also an equivalent feature in that part of the Arduino IDE user interface. In case you prefer to use that instead of the menu on the editor toolbar, I'll provide instructions you can follow to use it:

1. Select **File > Preferences...** (or **Arduino IDE > Settings...** for macOS users) from the Arduino IDE menus.
   The "**Preferences**" dialog will open.
1. Check the box next to "**☐ Show files inside Sketches**" in the "**Preferences**" dialog.
1. Click the "**OK**" button.
   The "**Preferences**" dialog will close.
1. Click the icon that looks like a folder in the "activity bar" on the left side of the Arduino IDE window.
   The "**SKETCHBOOK**" view will open in the left side panel.
1. Click the **❯** next to the sketch you have open in the Arduino IDE window.
   The list of files in the sketch will be shown.
1. Click the file you want to see in the editor.
   The tab of that file will be selected in the Arduino IDE editor panel.
