### ISSUE TITLE
Debugger for ESP32S3 Dev board used to be functional, now unsupported

### ISSUE THREAD

**Issue by frankcohen** [arduino/arduino-ide#2442]
### Describe the problem

Arduino IDE 2.2 supported ESP32S3 Dev Board debugging. Now I see an unsupported message. I'd like it back please.

### To reproduce

Select ESP32S3 Dev Module, click Debug icon.

### Expected behavior

Debugger works

### Arduino IDE version

Arduino IDE 2.3.3-nightly-20240423

### Operating system

macOS

### Operating system version

Sonoma 14.5

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @frankcohen. The ESP32 Dev Board is supported by the Arduino IDE integrated sketch debugger.

If you find that the "Start Debugging" button is disabled, this indicates that you have not selected a programmer from the IDE's **Tools > Programmer** menu. A programmer selection is now required when using Arduino IDE <=2.3.0 due to the addition to Arduino IDE of the capability to support multiple distinct types of debug probes (https://github.com/arduino/arduino-ide/pull/2281). So select **Tools > Programmer > Esptool** from the Arduino IDE menus and the "Start Debugging" button will now be enabled.

If you have any questions about using the Arduino IDE sketch debugger, or would like to discuss the subject, feel free to post over on [**Arduino Forum**](https://forum.arduino.cc/).
