### ISSUE TITLE
Serial interface locks up on Arduino Nano Matter on Mac

### ISSUE THREAD

**Issue by technoblogy** [arduino/arduino-ide#2469]
In some situations the Serial interface locks up on the Arduino Nano Matter, making further serial communication impossible until the board is reset. For details see:

[(https://github.com/SiliconLabs/arduino/issues/73)](https://github.com/SiliconLabs/arduino/issues/73)

I believe that the issue only occurs on Mac, but not on Windows.

**Comment by per1234** [comment]
Thanks for your report @technoblogy. I'm sure it is a problem with the board's firmware rather than the Arduino IDE application so I'll close this as off topic.

I'll monitor the issue in the `SiliconLabs/arduino` and if we do have an indication of an IDE bug through that investigation I'll reopen this.
