### ISSUE TITLE
intellisense does not work

### ISSUE THREAD

**Issue by lorypelli** [arduino/arduino-ide#2511]
### Describe the problem

I don't get it using Arduino IDE

### To reproduce

Open a `.ino` file

### Expected behavior

It should have same intellisense as C/C++ but it doesn't happear to

### Arduino IDE version

2.3.2

### Operating system

Windows

### Operating system version

Windows 11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @lorypelli. Thanks for your interest in this open source project. We require highly detailed formal bug reports in this issue tracker. Due to the lack of information in your report, it will be more appropriate for us to support you over on the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
