### ISSUE TITLE
No settings button (gear icon) and other 

### ISSUE THREAD

**Issue by kiterservice** [arduino/arduino-ide#298]
**Describe the bug one**
No settings button (gear icon)
**To Reproduce**
1. Fresh install arduino ide 2.0.0 beta 4
2. Open arduino ide 2.0.0 beta 4

**Describe the bug two**
Split screen for two windows of arduino ide 2.0.0 beta 4 not works. Window of ide has fixed minimum window wight (horisontal size).
**To Reproduce**
1. Fresh install arduino ide 2.0.0 beta 4
2. Open two windows of arduino ide 2.0.0 beta 4
3. Try to splitscreen or change wight.
![No settings 1](https://user-images.githubusercontent.com/65130624/113490122-df931980-94d0-11eb-8b70-f4524cddcbef.PNG)
![No settings](https://user-images.githubusercontent.com/65130624/113490123-e02bb000-94d0-11eb-9659-3a082a52eb06.PNG)
![Split screen](https://user-images.githubusercontent.com/65130624/113490124-e0c44680-94d0-11eb-890a-942a52eb4c00.PNG)

**Desktop (please complete the following information):**
 - OS:  Windows10 64
 - Version: e.g. 2.0.0 beta 4

**Additional context**
VS Code and platformio instaled .

**Comment by per1234** [comment]
>No settings button (gear icon)

This was an intentional change: https://github.com/arduino/arduino-ide/pull/209
You can access the advanced settings by opening the command palette (**Ctrl + Shift + P**), then searching for "Settings: Open Preferences".

>Describe the bug two

In the future, please open a separate issue for each distinct bug report.

>Window of ide has fixed minimum window wight (horisontal size).

Fixed by https://github.com/arduino/arduino-ide/pull/243
You can try it out in the nightly build of Arduino IDE 2.x:
https://www.arduino.cc/en/software#nightly-builds
In the future, please check the nightly build before submitting an issue to make sure it hasn't already been resolved.
