### ISSUE TITLE
Serial port keeps reconnecting when USB cable of board is disconnected

### ISSUE THREAD

**Issue by ednieuw** [arduino/arduino-ide#314]
When the USB cable is removed from the PC and the Serial monitor is open the IDE starts reconnection every second.
It is not possible no turn off the COM port because the Port: entry disappeared from the Tools menu
 
**Expected behaviour**
Automatic closure of the COM: port when removing the USB cable 
Not removing the Port: entry from the Tools menu when nothing is attached
Make it possible to disconnect a COM: port in the Tools -> Port: entry by deselecting the check mark

**Desktop 
 - OS: Windows 10
 - Version:  2.0.0 beta 4

**Comment by ednieuw** [comment]
Automatic reconnection is not convenient when more than one IDE is open or a serial terminal program
The port is may already connected by another program.

**Comment by StephenJD** [comment]
> When the USB cable is removed from the PC and the Serial monitor is open the IDE starts reconnection every second. It is not possible no turn off the COM port because the Port: entry disappeared from the Tools menu
> 
> **Expected behaviour** Automatic closure of the COM: port when removing the USB cable Not removing the Port: entry from the Tools menu when nothing is attached Make it possible to disconnect a COM: port in the Tools -> Port: entry by deselecting the check mark
> 
> **Desktop
> 
> * OS: Windows 10
> * Version:  2.0.0 beta 4

It is very annoying if you have multiple IDE's connected to different ports: when you disconnect one USB, its IDE auto-connects to one of the other IDE's ports. When you reconnect the USB you have to re-select the correct port.

I suggest:

Port-searching and connection ONLY happens when you try to upload or open the Serial Monitor.
If a previous port connection is lost, it remembers that port, and on attempting a reconnect, it first tries the previously connected port.

**Comment by larsinka** [comment]
If I'm using multiple Serial Monitors, one to monitor the USB serial and programming, one for BluetoothSerial, if upload the code and the Bluetooth port gets disconnected it won't reconnect. Instead I have to close the IDE and only then it works again.
