### ISSUE TITLE
Make Partitions clearly visible and allow easy definition

### ISSUE THREAD

**Issue by ullix** [arduino/arduino-ide#376]
I am frustrated with the overly brief description of Partitions in the A IDE's Tools->Partition Scheme. As I am using ESP32s with different amount of Flash combined with different File systems, I often need to dig into the Python code offerings of Espressif just to see the actual partitions. 

What I would like to see:

-  the option for a printout of the current partitions from within the IDE like this:

```
#       Name,       Type,   SubType,    Offset,     Size,      Flags
        nvs,        data,   nvs,        0x9000,     0x5000,
        otadata,    data,   ota,        0xe000,     0x2000,
        app0,       app,    ota_0,      0x10000,    0x140000,
        app1,       app,    ota_1,      0x150000,   0x140000,
        spiffs,     data,   spiffs,     0x290000,   0x170000,
#       ffat,       data,   fat,        0x290000,   0x170000,
```

- the option to include a file like **partitions.csv** with the above content, which the IDE would use to set the partitions

It was rumored that the second option already existed, but that was not true at least for my A 1.8.13 installation.

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @ullix .

This is something the ESP32 boards platform developers would need to implement, so you'd have to request it in that repository. The ESP32 boards platform is a 3rd party project unrelated to the Arduino IDE project hosted here.

If the ESP32 platform developers identify a specific feature that is needed from the Arduino IDE or Arduino CLI in order to enable that, then a well defined request for that feature is welcome (keeping in mind that the support for extension tools in Arduino IDE 2.x [has already been requested](https://github.com/arduino/arduino-ide/issues/30)).
