### ISSUE TITLE
Memcpy function not recognized

### ISSUE THREAD

**Issue by Markz878** [arduino/arduino-ide#387]
When using the memcpy function, IDE complains that "Use of undeclared identifier 'memcpy'clang(undeclared_var_use)".

**Comment by Markz878** [comment]
I noticed that in another function the memcpy function intellisense works correctly. Same thing with "Serial" class intellisense, it's only broken in one of the functions.. I'm using M-Duino family board.

**Comment by per1234** [comment]
Thanks for your report @Markz878. There have been some recent improvements to the [Arduino Language Server](https://github.com/arduino/arduino-language-server) that provides this capability in the IDE. These improvements are available from the latest release of the Arduino IDE.

Please try again with [the latest build](https://github.com/arduino/arduino-ide#nightly-builds) of the Arduino IDE and let us know whether or not the bug is fixed for you.

**Comment by per1234** [comment]
Closing due to lack of response.

@Markz878 if you will provide the requested information by commenting here, I'll be happy to re-open this issue.
