### ISSUE TITLE
Incorrect handling of Legacy format libraries by File > Examples menu

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#40]
### Describe the bug

The examples of installed "1.0 format" libraries are not correctly handled by the IDE's **File > Examples** menu.

##### Background:

[The "1.5 library format"](https://arduino.github.io/arduino-cli/dev/library-specification/#library-layout) is attained by the addition of [a `library.properties` metadata file](https://arduino.github.io/arduino-cli/dev/library-specification/#library-metadata) to the library root folder. The decade of Arduino library development before the introduction of this format produced many "1.0 format" libraries, which are still supported by the Arduino development software for the sake of backwards compatibility.

### To Reproduce

1. Download https://github.com/arduino-libraries/RestClient/archive/refs/heads/master.zip
   NOTE: this is just an arbitrary 1.0 format library. The issue will occur with any such library.
1. Select **Sketch > Include Library > Add .ZIP Library...** from the Arduino IDE menus.
1. Select the downloaded file (`RestClient-master.zip`).
1. Click the <kbd>Open</kbd> button.
1. Close the Arduino IDE.
1. Start the Arduino IDE.
   (there is a separate bug that causes the examples of libraries installed via **Add .ZIP Library...** to not be shown until restart)
1. Open the **File > Examples** menu
   Note that the expected "**RestClient-master**" entry is missing.
   Note that there is a blank entry in the menu that contains all examples of all installed 1.0 format libraries:

![image](https://user-images.githubusercontent.com/8572152/139392704-370257bd-0fad-40a8-9052-b1129a74a886.png)

### Expected behavior

Handling of "1.0 format" libraries to be done the same as in the classic Arduino IDE:

A menu entry is added to the **File > Examples** menu for each library which provides example sketches, regardless of its format. Since 1.0 format libraries don't provide a name via the `name` field of the `library.properties` metadata file, the name is determined by the name of the library's installation folder.

![image](https://user-images.githubusercontent.com/8572152/139394393-253e1e61-2739-403c-9bbe-1b00747c2e21.png)

### Desktop

OS: Windows 10
Version: 2.0.0-beta.2-snapshot.f9730ab
Date: 2021-02-18T13:01:31.751Z
CLI Version: 0.16.0 alpha [c977a238]

#### Incidence in platform bundled libraries

The original demonstration of this issue used the [platform bundled libraries](https://arduino.github.io/arduino-cli/dev/platform-specification/#platform-bundled-libraries) of the "Arduino Mbed OS Boards" platform. The bug still affects versions of that platform up to, and including, version 2.5.2:

![Clipboard01-2](https://user-images.githubusercontent.com/1894487/109182916-b672c100-778d-11eb-9d99-987685291dc7.png)

After 2.5.2, the platform's libraries were converted to "1.5 format" as a workaround for this bug (https://github.com/arduino/ArduinoCore-mbed/pull/340), so the later versions of the platform are not affected. For this reason, I changed the demo to using a manually installed "1.0 format" library, which is a less dramatic demo.

However, it may be that "1.0 format" libraries are still relatively common in bundled libraries of 3rd party platforms, since they are not distributed through Library Manager, which has been the primary reason for converting libraries to the 1.5 format.

#### Reports

- Originally reported publicly (incidentally) at: https://forum.arduino.cc/t/invalid-dfu-suffix-signature/679244/11
- Originally reported internally by @per1234
- https://forum.arduino.cc/t/libraries-included-with-board-dont-show-up-as-expected/1032334

**Comment by mjs513** [comment]
In lieu of creating a separate issue I am going to expand on this issue. 
OS:
Windows 10x64
Version: 2.0.0-rc3-nightly.20220201
Date: 2022-02-01T03:08:59.105Z
CLI Version: 0.20.2 [13783819]

**Incidence in platform bundled libraries (Expanded)**
While experimenting with the first version of the Teensyduino Board Manager version for testing the Arduino IDE and Arduino IDE 2,  it appears that:
**...., it may be that "1.0 format" libraries are still relatively common in bundled libraries of 3rd party platforms, since they are not distributed through Library Manager, which has been the primary reason for converting libraries to the 1.5 format.**
is going to be a continuing problem with some 3rd party platforms.

Problem description:  Teensyduino installs its own set of libraries.  Some of these libraries are contributed from other sources than PJRC.  An example is Bill Porter's EasyTransfer and EasyTransferIC libraries.  However, these are in the 1.0 library formated as noted above.  To convert the libraries to 1.5 I added a library.property file for both:
```
name=EasyTransfer
version=1.7
author=Bill Porter
maintainer=Bill Porter
sentence=Transfer data between Arduinos over serial connection.
paragraph=The purpose of this library is to make it easy for the everyday Arduino user working on projects with multiple Arduinos communicating with each other and sharing data over Serial connections.
category=Communication
url=https://github.com/madsci1016/Arduino-EasyTransfer/tree/master/EasyTransfer
architectures=*
```
This seemed to resolve the issue and showed those libraries in the examples list for the Teensy board selected.  However, when I try to open one of the examples in the EasyTransfer library it fails to load the sketch.

Screenshots:
![Capture](https://user-images.githubusercontent.com/5366213/152457782-bf26fa9a-0498-453f-996f-835c832b5bb0.PNG)
![Capture1](https://user-images.githubusercontent.com/5366213/152457798-f37d458c-03cb-4aae-abe8-e49560763ff3.PNG)

This issue with 1.0 library format is not limited to Teensy.  If I select Arduino Uno I am seeing the same thing:
![Capture2](https://user-images.githubusercontent.com/5366213/152457860-1000222c-c0be-4ef5-9a98-910af957ff7f.PNG)

**Comment by per1234** [comment]
Hi @mjs513.

> when I try to open one of the examples in the EasyTransfer library it fails to load the sketch.

That is caused by an unrelated bug: https://github.com/arduino/arduino-ide/issues/518

I can see that the "EasyTransfer" library examples use the `.pde` extension:

https://github.com/PaulStoffregen/Arduino-EasyTransfer/tree/06f6d696f3c8c7d726043af9581a3a959c7a3e2e/EasyTransfer/examples/EasyTransfer_2Way_wPot_Example

This issue (https://github.com/arduino/arduino-ide/issues/40) only affects the way the examples menu is organized. Once you select an example from under that blank menu item, it opens just like any other example.

https://github.com/arduino/arduino-ide/issues/518 occurs when you try to open any example that uses the deprecated `.pde` file extension, regardless of whether it is from a "legacy" format library or not.

>This issue with 1.0 library format is not limited to Teensy. If I select Arduino Uno I am seeing the same thing

Yes. It is universal.

**Comment by mjs513** [comment]
Hi @per1234 

Thanks for responding so quickly.  At least for me still learning about the new IDE and beginning to get use it the more and more I use it.  You all did a nice job with it!

So basically we have to convert all pde's to ino's it I am understanding issue #518 correctly.#58 

Thanks again Mike

**Comment by PaulStoffregen** [comment]
FWIW, I've renamed every old .pde to .ino in all my libraries.  Wow, there were a *lot* of them.

Probably going to wait into a nightly build uses pluggable monitor (issue #769) before I package up another version.  When I do, only a small number of files actually meant for Processing with have .pde.
