### ISSUE TITLE
Auto format configuration doesn't match classic Arduino IDE

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#42]
**Describe the bug**
The auto format configuration used by the Java IDE represents a de facto Arduino code style that has been established and consistent for years.
The configuration is defined here:
https://github.com/arduino/Arduino/blob/1.8.13/build/shared/lib/formatter.conf
The documentation is here:
http://astyle.sourceforge.net/astyle.html
I personally find it disturbing when running an auto format on a sketch based on an official sketch or documentation snippet results in formatting changes to the existing code and I'm sure this could cause confusion for beginners. My experience indicates that changing the formatting of the official sketches and documentation snippets may be extremely difficult politically.
So I think it's very important to have continuity in the formatting configuration between the two IDE. If we do make changes to the official code style, the change should be based on a conscious decision, rather than just an arbitrary change.
This is the sort of thing that becomes more problematic to change as time goes on.

**Desktop (please complete the following information):**
OS: Windows 10
Version: 2.0.0-beta.2-snapshot.f9730ab
Date: 2021-02-18T13:01:31.751Z
CLI Version: 0.16.0 alpha [c977a238]

**Additional context**
https://github.com/arduino/arduino-pro-ide/issues/339
https://github.com/arduino/Arduino/issues/3941

[ originally reported by @per1234 ]

**Comment by tigoe** [comment]
+1 this. It's the feature I use most when teaching. Until it's available I can't use the 2.0 IDE in class.

**Comment by ubidefeo** [comment]
@tigoe 
there's a patch in the works.
should be in the next beta which is not far from completion :)

**Comment by tigoe** [comment]
Update, still does not appear to work in beta 6.

**Comment by ubidefeo** [comment]
hi @tigoe 

we're back on this issue, which board have you selected?
we know that because it requires some pre-compilation it can be slower on mbed based boards,
but it is working if you have a board selected

**Comment by tigoe** [comment]
Weird, why does autoformat depend on the board type?

I've been using the nano 33iot, the mkr 1010, the Uno, and the nano 33ble
with the new ide. Autoformat not working on any of them.

**Comment by tigoe** [comment]
Update, using 2.0.0-beta.11:

Auto format still not working. 

test:
* make new sketch
* write blink code, without tabbing any lines
* press cmd-T
* Nothing happens

**Comment by per1234** [comment]
We have now resolved this issue to the extent that is possible.

This consisted of the following:

- Reduce differences by using a custom **ClangFormat** configuration in the Arduino IDE:
  https://github.com/arduino/arduino-language-server/commit/4083356ae32dee76c1d8b35537ba8ff2ecec4d09
- Allow user configuration to reduce friction from unavoidable changes:
  https://github.com/arduino/arduino-ide/pull/1019
- Document user configuration system:
  - https://github.com/arduino/docs-content/pull/317
  - https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-customize-auto-formatter
- Validation system to ensure unintentional changes are not introduced by ClangFormat updates:
  - https://github.com/arduino/tooling-project-assets/pull/250
- Use new **ClangFormat** configuration options to further reduce differences:
  - https://github.com/arduino/tooling-project-assets/pull/254
  - https://github.com/arduino/arduino-ide/pull/1285

We encourage those who have published Arduino code to run an "**Auto Format**" on it at the next release in order to bring it into compliance with Arduino's now slightly more comprehensive standardized code style. Due to the efforts to achieve consistency in this style, any changes that result are likely to also be compliant with the more permissive Arduino IDE 1.x "**Auto Format**".

For those using another editor for development, or with automated formatting checks, Arduino's official **ClangFormat** configuration file is hosted here:

https://raw.githubusercontent.com/arduino/tooling-project-assets/main/other/clang-format-configuration/.clang-format
