### ISSUE TITLE
Can't see the hex files after exporting compiled binary

### ISSUE THREAD

**Issue by Carnoval15** [arduino/arduino-ide#454]
**Describe the bug**
The pro-IDE isn't generating the hex file!

**To Reproduce**
1. easily, make a project, use a simple code
2. click: "Export compiled binary"
3. Check the sketch folder
4. And now you can't see the hex file

**Expected behavior**
There must be 2 files with hex extension

**Screenshots**
![VzR3GIe8WJ](https://user-images.githubusercontent.com/67748205/125776681-f8b7c9d2-f4ce-4201-a202-619e89ca5a88.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H1

Can anyone fix this? or help me if I do the wrong thing. Thx!

**Comment by per1234** [comment]
Hi @Carnoval15. Thanks for taking the time to submit an issue.

The exported binaries are now located in the `build/arduino.avr.uno` subfolder of the sketch folder.

This was an intentional change, so the different location should not be seen as a bug, but we definitely need to document the changed behavior to allow a painless migration from the classic Arduino IDE to Arduino IDE 2.x, so the lack of such documentation (as far as I know) could certainly be considered a bug.

**Comment by Carnoval15** [comment]
I see! I found the hex files in there.
thanks for helping!
