### ISSUE TITLE
Erratic left-right Scrolling of Output Window in IDE version 2.0.0

### ISSUE THREAD

**Issue by moefear85** [arduino/arduino-ide#495]
Hello,

The Output window (which shows everything during compilation/upload), scrolls also in the right direction to the end of the line and then jumps back to the initial left position for the next output line, and repeats this, very fast. It makes it impossible to understand what is currently going on. This happens both on Windows and Linux.

Clicking the Scroll-Lock icon to disable scrolling isn't really helpful, since it also disables downwards scrolling, which however I want to keep.

**Comment by robonxt** [comment]
This issue is still present as of the 2022.04.16 nightly build, not to mention it seems to make the output window lag when the "show verbose compiling messages" is enabled, as it finishes uploading to the board before the text is finished loading (ESP32 code)

**Comment by per1234** [comment]
>it seems to make the output window lag

I have seen this claim by multiple users now. I'm not at all convinced that the scrolling is related to the lag. My impression is that the lag is something that occurs regardless of whether there is scrolling. It is simply that there is a horrible bottleneck somewhere in the output pipeline. The lines that require scrolling will always contain more data that must trickle through that bottleneck, so that output will lag more for that reason alone.

The output bottleneck is already tracked in dedicated issues, so let's restrict discussion of it to those unless someone has more than coincidence to back the idea that the scrolling is related:

- https://github.com/arduino/arduino-ide/issues/68
- https://github.com/arduino/arduino-ide/issues/405

**Comment by ubidefeo** [comment]
@per1234 
isn't this fixed yet?
we have done a lot of work on the output window since this issue was reported including some visual glitches caused by the chaining of text

**Comment by moefear85** [comment]
this issue has been resolved atleast as of 2.0.0-rc9
