### ISSUE TITLE
Language mode is set to C++

### ISSUE THREAD

**Issue by AlbyIanna** [arduino/arduino-ide#529]
The status bar shows "C++" when a `.ino` tab is selected. The official proclamation is that `.ino` files are written in Arduino Programming Language, not C++.

I'm not convinced this thing is worth the space it takes up on the GUI even if it was working correctly. Does the language mode menu you get when you click on it actually offer anything of value in this application? I've been messing with it and not found any. It seems like it's just something that will confuse beginners and be ignored by advanced users. Even in VS Code, where it would be much more likely to be of use due to it being a general purpose editor, I don't recall ever having used it. Has @giannicolab reviewed it?

![image.png](https://zube.io/files/arduino/99214c27d0b07e389f70cd38a74c7066-image.png)

### Environment

Version: 2.0.0-beta.11-snapshot.da6b66f
Date: 2021-10-06T08:06:21.909Z
CLI Version: 0.19.1 alpha [718bbbf2]
OS: Windows 10

**Comment by Silver-Fang** [comment]
Maybe the development team is just trying to pull users back from VS Code. How? Just make an Arduino-specific version of VS Code 😄

**Comment by iamart** [comment]
a bit off topic comment, but what is the point of `The official proclamation is that .ino files are written in Arduino Programming Language`? It is just C++ in the end but with the Arduino framework on top. It actually brings more confusion by calling it that.

**Comment by per1234** [comment]
This issue no longer occurs.

I bisected the fix to the unexpected source at https://github.com/arduino/arduino-ide/commit/84109e416ad15d88c076a1fc87bca553569c9b57 / https://github.com/arduino/arduino-ide/pull/1085. But I'll just be happy that it is fixed even if the way that occurred is not clear to me.

**Comment by mtfy** [comment]
.ino files are using Arduino wrappers around C++ so the language is C++

**Comment by per1234** [comment]
Hi all. There is a GitHub "discussions" repository Arduino created recently for the purposes of discussing the "Arduino Language":

https://github.com/arduino/language/discussions

You are very welcome to start a thread over there to discuss this subject. Someone actually brought it up over there, but in somewhat of a "hijack" manner on an unrelated thread. I was disappointed that they never created a dedicated thread for it as I suggested because this is a subject matter I am also interested in.

But as for discussing it here, it is not really appropriate. This issue is solely about the status bar item in the Arduino IDE UI. Since that item no longer exists, there really isn't any need for further discussion of the subject unless someone feels that it provided significant value to the Arduino IDE users and should be added back.
