### ISSUE TITLE
Dark theme is used on clean start despite "Light (Arduino)" being the default

### ISSUE THREAD

**Issue by AlbyIanna** [arduino/arduino-ide#530]
When the Arduino IDE is started from a clean system (no configuration files from a previous IDE run), it is using the dark theme even though the default preference setting is for the light theme.

### Steps to reproduce

1. Delete the IDE's configuration folders (e.g., `C:\Users\per\.arduinoIDE`, `C:\Users\per\AppData\Roaming\arduino-ide`, 
1. Start the IDE. Note that it is in dark mode
1. Open **File > Preferences**. Note that the theme is set to "Light (Arduino)".

![image.png](https://zube.io/files/arduino/3795fbd5c6a0502bcb9afcab12970d1e-image.png)

### Expected behavior

The IDE uses the "Light (Arduino)" theme by default.

### Environment

Version: 2.0.0-beta.11-snapshot.da6b66f
Date: 2021-10-06T08:06:21.909Z
CLI Version: 0.19.1 alpha [718bbbf2]
OS: Windows 10

### Additional information

This does not occur when the same steps are followed with 2.0.0-beta.11

**Comment by fstasi** [comment]
The expected behaviour is that the Arduino Light theme should be used when the OS current theme is light, the Arduino Dark theme should be used when the OS  OS current theme is dark.

The issue is also that at the moment, when the OS has dark current theme, IDE2 default to Theia Dark, rather than Arduino Dark theme.
