### ISSUE TITLE
Additional sidebar items like Outline or Explorer not remembered

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-ide#538]
**Describe the bug**
Additional sidebar items like Outline or Explorer must added after every startup

**To Reproduce**
1. Add Outline with command "Toggle Outline View"
2. Close the App and then restart
3. Outline item on sidebar is missing

**Expected behavior**
The app should remember the additional sidebar views

**Screenshots**
Configured:
<img width="1421" alt="sidebar" src="https://user-images.githubusercontent.com/6450325/136657287-aa99f750-e666-49ed-ba6c-62f0854af416.png">
After restart:
<img width="1421" alt="sidebar start" src="https://user-images.githubusercontent.com/6450325/136657305-47f773fe-4644-4c6a-adb7-7801ec569273.png">
**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 11.6

**Additional context**
This happens also on Explorer view

**Comment by per1234** [comment]
Thanks for your report **sstaub**. This has been fixed since Arduino IDE 2.0.0-rc1 (but we missed closing it at that time).

I'm not sure exactly which change was responsible, but I would guess https://github.com/arduino/arduino-ide/pull/610

Please note that the workbench is configured on a sketch by sketch basis. It is necessary to configure the workbench as you like for a given sketch, but after that the configuration will be remembered each time you open the sketch.
