### ISSUE TITLE
Unable to close split tabs

### ISSUE THREAD

**Issue by BanksySan** [arduino/arduino-ide#552]
**Describe the bug**
<kbd>Ctrl</kbd> + <kbd>\\</kbd> splits the view horizontally and opens a duplicate tab in the new section.

There's no way to close the split views though, even closing the IDE doesn't fix it as it remembers your last layout and _helpfully_ opens up in the state you left it.

**To Reproduce**
1. Open project.
2. Split screen with <kbd>Ctrl</kbd> + <kbd>\\</kbd>.

**Expected behavior**
There's a method to close views.

**Screenshots**

![image](https://user-images.githubusercontent.com/996280/137393426-c679a600-7ed5-466d-93e1-42df3dde9e75.png)

**Desktop (please complete the following information):**
**Edition**	Windows 10 Home
**Version**	21H1
**OS build**	19043.1288
**Experience**	Windows Feature Experience Pack 120.2212.3920.0

**Additional context**

IDE:

**Version**  2.0.0-beta.12
**Date**  2021-10-07T07:55:54.325Z
**CLI Version**  0.19.1 alpha [718bbbf2]

**Comment by BanksySan** [comment]
As things are, any suggestion on how I get rid of the tabs I have open?

![image](https://user-images.githubusercontent.com/996280/137599646-06dc222b-b35d-4bb4-b399-0adfd43cd3b9.png)

### Keyboard shortcut

> The suggestion to add a "Close" item to the tab control menu is reasonable though. However, this is a departure from the current UI convention for closing non-required tabs (e.g., File > Advances > Keyboard Shortcuts), which is the more visible X icon to the right side of the tab text.

The keyboard shortcuts have several entries for closing tabs, non of them work though, the tabs stubbornly stay where they are.

![image](https://user-images.githubusercontent.com/996280/137599766-7b0d7a60-6ec1-4d61-abc1-35a359f4ac93.png)

**Comment by per1234** [comment]
>any suggestion on how I get rid of the tabs I have open?

You can reset the IDE by deleting this folder on Windows:
```
C:\Users\<user name>\AppData\Roaming\arduino-ide
```

**Comment by skypanther** [comment]
I'm having the same issue as the original submitter, though I'm working on a Mac running Big Sur. Deleting a config file as per1234 suggests might work, but is hardly a good solution.

I'm not sure why you hide the X in the tab that VSCode usually provides. You've also removed the View: Split Editor Single command which closes all the split windows. You hide the View menu. I'm actually dumbfounded how many unnecessary changes from VSCode have been made to create this IDE.

**Comment by per1234** [comment]
>Deleting a config file as per1234 suggests might work, but is hardly a good solution.

I apologize if I somehow gave the impression it was a solution. It is only a workaround. The Arduino IDE developers will close this issue once there is a solution.

> unnecessary changes from VSCode

Arduino IDE 2.x is built on the open source [Eclipse Theia](https://theia-ide.org/) framework, not VS Code. Since they are based on some of the same technologies and design philosophies, there are some resemblances to VS Code, but they are not the same. Arduino IDE 2.x is not a variant of VS Code. Arduino IDE 2.x is its own project and Arduino has its own vision for that project. If you want to participate in a positive manner in making that vision a reality, you are welcome. If you have some other vision, then feel free to make your own IDE.

**Comment by ch4bes** [comment]
I've found that I'm able to close open split panes using the Explorer sidebar, where it shows "OPEN EDITORS". Each instance has an "X" on the right side that can be used to close it.

Would still be nice to have a way of closing the panes from the editor itself, in addition to a keyboard shortcut.

**Comment by per1234** [comment]
The bug is more serious since https://github.com/arduino/arduino-ide/pull/791 because the split editor capability is now accessible via the primary UI:

![image](https://user-images.githubusercontent.com/8572152/153775270-f92cdc52-f627-434f-8bab-23e53fc2a39b.png)

**Comment by tibor-vavra** [comment]
![image](https://user-images.githubusercontent.com/4319021/155876312-d218924f-e73f-425b-8e40-5f8c8c0456aa.png)

**Comment by mudgalp** [comment]
this worked for me..
Thank you

**Comment by road-t** [comment]
That's INSANE not to have close tab button. I had to remove the settings db to get rid of 5 split windows (erroneously pushed cmd + \ instead of cmd + /). That is ridiculous.

**Comment by road-t** [comment]
> @msujew we decided to disable split tabs at all for now

facepalm

**Comment by CptHolzschnauz** [comment]
Oh nooo.. please not...

**Comment by michael-vrba** [comment]
> facepalm

![image](https://user-images.githubusercontent.com/100512287/161248354-39e62b69-c483-4be3-9f40-ebe7d7fbbe37.png)

**Comment by per1234** [comment]
Hi all. Let's keep this issue focused on the original subject, which is the current inability to close split editors. Disabling the feature that is not working properly is the planned mitigation measure for this specific issue.

We will dedicate https://github.com/arduino/arduino-ide/issues/909 to tracking the request for adding a fully functional split editor capability.

Any discussion about that should be done over there, and I will request that people only comment there if you have something constructive to add. If you only want to express general support or disagreement, then use the [Reactions feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) so that we don't generate a bunch of noise for the people who are watching the repository in order to keep up with the development work.

**Comment by CptHolzschnauz** [comment]
You are right. Thank you per1234. I misunderstood in a way that the feature was suspended.

**Comment by numeralz** [comment]
Guys, I'm so sorry, but I was sooo excited that Arduino IDE has migrated to something that resembles VSCode, but this issue is simply puzzling.

Certainly, integrating the open-source vs-code IDE interface **AS-IS** with **default user interface behavior almost everyone is already used to** must take **less effort** than adding these kinds of customizations that **prevent basic functionality**?

Having to google to look up how to close a tab that I accidentally split 3 times is insane, and confusing to hobbyists, new or advanced.

I just don't understand, because the customization to remove an existing feature must have been intentionally planned, and then developer time allocated to make this customization happen. It puzzles me - why was this such an important feature? Do newbies accidentally close tabs too often, and then complain about it, that it was necessary to disable the close tab? 

I even accidentally "deleted" my file because I thought this was the close feature.

Aside from this, I am extremely excited about the new IDE and think it has **insanely great** potential to improve the development workflow on the platform. Hats off to everyone working on this.

**Comment by Zechs2205** [comment]
This issue still persists. Get your shit together like wtf is this. I cant even F1 and find close. Its on me for using your shitty IDE

**Comment by michael-vrba** [comment]
Yes, I agree. How can they program the programming interface if they can't split the window and allow it to close/collapse. They solve the problem by disabling the option. Two years ago!
