### ISSUE TITLE
Show 'progress' indicator during verify/upload

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#575]
**Is your feature request related to a problem? Please describe.**

There is no sign of activity from the IDE for long periods of time while compiling or uploading large sketches with the default setting of verbose output disabled.

**Describe the solution you'd like**

Add a visual progress indicator.

The classic Arduino IDE has this:

![progress.png](https://zube.io/files/arduino/03a7292661a4f497fe2746143e8cdddc-progress.png)

**Desktop (please complete the following information):**
- OS: Windows 10, Ubuntu 20.04
- Version: 2.0.0-beta.12-nightly.20211020
  Date: 2021-10-20T03:02:52.486Z
  CLI Version: 0.19.1 alpha [718bbbf2]

**Additional context**

Originally requested at:

- https://forum.arduino.cc/t/no-compilation-or-uploading-progress-bar-for-the-arduino-ide-2-beta/876983
- https://forum.arduino.cc/t/compile-progress-status-bar/908536
- https://forum.arduino.cc/t/ide-2-0-rc5-compile-progress-bar/977994

Related:

- https://github.com/arduino/arduino-ide/issues/279
- https://github.com/arduino/arduino-ide/pull/305

**Comment by giannicolab** [comment]
This has been tackled as part of the output panel redesign. Files are on Figma: https://www.figma.com/file/NRbWNL7Gvzq77G8ljDVJsl/IDE-2.0---DEV?node-id=1678%3A17655

**Comment by kittaakos** [comment]
For the record, there is no progress indication for `upload`/`upload using programmer`/`burn bootloader` commands in the Java IDE. Since the following gRPC response types do not have a `progress`/`task` property, the IDE2 can show the desired definite progress only for the `verify` command, the rest will run with an indefinite progress indication.
 - [`UploadResponse`](https://github.com/arduino/arduino-cli/blob/5332ffdafc951e96fb7576e4a5b520c1658fb015/rpc/cc/arduino/cli/commands/v1/upload.proto#L64-L69),
 - [`UploadUsingProgrammerResponse`](https://github.com/arduino/arduino-cli/blob/5332ffdafc951e96fb7576e4a5b520c1658fb015/rpc/cc/arduino/cli/commands/v1/upload.proto#L110-L115), and
 - [`BurnBootloaderResponse`](https://github.com/arduino/arduino-cli/blob/5332ffdafc951e96fb7576e4a5b520c1658fb015/rpc/cc/arduino/cli/commands/v1/upload.proto#L142-L147)
