### ISSUE TITLE
Compiler fatal error on valid Adafruit library multiline comment

### ISSUE THREAD

**Issue by jackthese** [arduino/arduino-ide#598]
**Describe the bug**
In the Adafruit IO library (Adafruit_Definitions.h), the following valid code
```cpp
#define AIO_FEED_NAME_LENGTH                                                   \
  258 ///< Maximum length of an Adafruit IO Feed    \
                                  ///< Name; 128 + 1 + 128 for the group, a dot \
                                  ///< , and actual feed name.
#define AIO_DATA_LENGTH                                                        \
  45 ///< Maximum length of data sent/recieved from Adafruit IO
#define AIO_CSV_LENGTH                                                         \
  AIO_FEED_NAME_LENGTH + 4 ///< Maximum comma-separated-value length from \
                           ///< Adafruit IO
```

threw the following fatal errors:
```
c:\Users\jackr\Documents\Arduino\libraries\Adafruit_IO_Arduino\src/AdafruitIO_Definitions.h:128:7: error: multi-line comment [-Werror=comment]
258 ///< Maximum length of an Adafruit IO Feed \
^
c:\Users\jackr\Documents\Arduino\libraries\Adafruit_IO_Arduino\src/AdafruitIO_Definitions.h:134:28: error: multi-line comment [-Werror=comment]
AIO_FEED_NAME_LENGTH + 4 ///< Maximum comma-separated-value length from \
^
The compiler stopped with "Compilation error: Error: 13 INTERNAL: exit status 1"
```

The problem seems to go away if the backslashes at the end of the lines are removed.

**Additional context**
I submitted the above to the AdafruitIO forum and their response was (from Administrator brubell):
"I don't think Arduino sketches should throw errors at the end of a supported multiline comment, it seems to be be a bug within Arduino IDE 2.x Beta."

**Comment by per1234** [comment]
Hi @jackthese. Note this part of the error message: `-Werror=comment`

What does this mean, first let us look at the `-Werror=` part
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-w
```
-Werror=
Make the specified warning into an error. The specifier for a warning is appended; for example -Werror=switch turns the warnings controlled by -Wswitch into errors.
```

Now we look at the `comment` part:
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcomment
```
-Wcomment
-Wcomments
Warn whenever a comment-start sequence ‘/*’ appears in a ‘/*’ comment, or whenever a backslash-newline appears in a ‘//’ comment. This warning is enabled by -Wall.
```
So you can see that the compiler is telling you that it has been configured to upgrade something that is normally a warning  (a comment pattern that is a common source of bugs) into an error.

The ESP32 boards platform authors added this `-Werror` compiler flag in order to enforce the proper development practice of producing warning free code. There is an oddity in how they did it though, which you can see here:
https://github.com/espressif/arduino-esp32/blob/2.0.0/platform.txt#L86-L91
```
# Arduino Compile Warning Levels
compiler.warning_flags=-w
compiler.warning_flags.none=-w
compiler.warning_flags.default=
compiler.warning_flags.more=-Wall -Werror=all
compiler.warning_flags.all=-Wall -Werror=all -Wextra
```
Note that the `-Werror` flag is only set on the `compiler.warning_flags.more` and `compiler.warning_flags.all`. This means that if you have **File > Preferences > Compiler warnings** set to the "None" or "Default" settings, then all those ugly little compiler warnings are no problem at all. The problem this causes is that firmware developers who write the code with compiler warnings also often have their compiler warnings turned off. So the code compiles just fine for them, but then errors for some users depending on their IDE settings.

So all this is to say that Arduino IDE 2.x is working just fine and the bug is Adafruit's library code. You are welcome to report this to them, or you can just set **File > Preferences > Compiler Warnings** to "Default" and the code will compile fine.
