### ISSUE TITLE
Library Manager install fails ~silently if dependency not available

### ISSUE THREAD

**Issue by butor32** [arduino/arduino-ide#621]
### Describe the problem

Installation of version 3.0.0 of the "**Forced-BME280**" by Jocchem van Kranenburg via Library Manager fails silently.

### To reproduce

1. Open the "**LIBRARY MANAGER**" view.
1. Type `forced-bme280` in the "**Filter your search...**" field.
1. Select "**3.0.0**" from the dropdown version menu in the "**Forced-BME280**" library entry.
1. Click the "**INSTALL**" button.

🐛 The library installation fails silently.

### Expected behavior

The cause of the problem is clearly communicated to the user when it is not possible to install a library.

#### Original report

2.0.0-beta.12

#### Last verified with

964ea3bc0cb51c87592757ca7b8b73002c475033

### Operating system

- Windows
- Linux

### Operating system version

- Windows 11
- Debian Blueseye

### Additional context

An error is shown in the terminal window:

```text
root ERROR Request listDependencies failed with error: 9 FAILED_PRECONDITION: No valid dependencies solution found: dependency 'stdint' is not available
```

However, the message only flashes for an instant in the Arduino IDE window; so fast that the user could never read it.

### Additional reports

- https://github.com/arduino/library-registry/issues/1895
- https://github.com/arduino/library-registry/pull/2330#issuecomment-1370566965

<a name="workaround"></a>

#### Workaround

Use the "**Add .ZIP Library...**" method to install the problematic library:

https://docs.arduino.cc/software/ide-v1/tutorials/installing-libraries#importing-a-zip-library

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @butor32. Thanks for your report. This error is caused by the "Forced-BME280" having invalid metadata. I have submitted a pull request to correct this problem in the library:

https://github.com/JVKran/Forced-BME280/pull/9

That will only fix one specific instance of this problem, and even then the previous versions of the library will still have it. Arduino does not control the metadata of the thousands of Library Manager libraries, so it is inevitable that some will have minor problems in their metadata such as this one. It could even happen through no fault of the library author in the event the name of one of its dependencies is changed.

So it is essential for the Arduino IDE to be designed to function even in the face of problematic external data. At the very minimum, the problem should be clearly communicated to the user. But the better approach is to handle it gracefully, as is done by the classic Arduino IDE. Even with Arduino CLI, although the standard installation fails, it does so with a clear error message and the user can still install the library via the use of the `--no-deps` flag.

We can use this issue to track that need to improve the user experience when this happens.

**Comment by butor32** [comment]
Hi @per1234,
For me you have a second bug, when a user add a library you must control metadata before you add library into your base.
Best regard

butor32

**Comment by per1234** [comment]
Thanks for your suggestion! We do check the validity of the metadata before accepting the library into Library Manager. We do detect this condition and warn the library submitter about it ([example](https://github.com/arduino/library-registry/pull/688#issuecomment-973137247)). However it is only treated as a warning. The reason for that is multiple interdependent libraries may be submitted simultaneously, which results in a spurious failure of the check.

We also check the metadata before adding each release of the library once accepted. However, the specific contents of this field has not historically been validated because the original system did not have that capability. That means there is a tricky situation where we have a legacy of library releases such as those of the "Forced-BME280" library in the database and those could be affected retroactively if we made this check more strict.

**Comment by kittaakos** [comment]
It turned out that the problematic part was listing the dependencies before installing it. I will add a quick fix.
