### ISSUE TITLE
Rightmost tab is selected by default

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#643]
## Describe the bug

Arduino sketches may consist of multiple files, which are shown in the Arduino IDE as tabs when that sketch is open. The file with name matching the sketch name is always leftmost in the tabs. Since the `.ino` files are concatenated in order, the leftmost file is always the primary file.

For this reason, the leftmost tab should be selected by default.

🐛 However, the IDE currently selects the rightmost by default. This results in a less friendly experience for beginners.

## To Reproduce

1. Download this demonstration multi-file sketch: [MultipleFiles.zip](https://github.com/arduino/arduino-ide/files/7631481/MultipleFiles.zip)
1. Unzip the downloaded file.
1. Select **File > Open** from the Arduino IDE menus.
1. Select the `MultipleFiles.ino` file from the unzipped sketch folder.
1. Click the <kbd>Open</kbd> button.

🐛 Note that the second tab (`SomeTab.ino`) was selected.

## Expected behavior

Select the leftmost tab by default.

On subsequent opens of the sketch, it is fine to remember the previous tab selection.

## Desktop

- OS: Windows 10
- Version: 2.0.0-rc1-snapshot.f0d9894
Date: 2021-11-30T16:25:41.414Z
CLI Version: 0.20.1 [abb21449]

## Additional context

Although the multi-file sketch capability is often used for more advanced sketches, this is not always true. For example, **File > Examples > 02.Digital > ToneMelody** is an introductory level example sketch.

**Comment by ubidefeo** [comment]
This issue is also happening on Mac OS.
What I have noticed is that with a clean system, at the first Sketch loading, the tabs are open and selected in alphabetical order (except for the main `.ino` file which is opened first).
The focus is shifted to the last opened tab.
On my Mac I see the tabs loaded at 2 seconds distance and the focus happening.
The last tab is selected and focussed and so it stays.

When the Sketch is closed, the currently selected tab will be remembered, and it will be in focus at the next loading (see screenshots)

<img width="927" alt="CleanShot 2022-11-02 at 14 14 07@2x" src="https://user-images.githubusercontent.com/1894487/199501454-24e68208-03a1-4b72-88c7-300c049c1ecd.png">
<img width="1035" alt="CleanShot 2022-11-02 at 14 14 44@2x" src="https://user-images.githubusercontent.com/1894487/199501489-709d7ee1-23a1-4cbd-8de4-9e5770306fee.png">
<img width="851" alt="CleanShot 2022-11-02 at 14 15 22@2x" src="https://user-images.githubusercontent.com/1894487/199501515-2e72188e-671f-402e-9b30-013048b5ad78.png">
