### ISSUE TITLE
Tabs also show the path 

### ISSUE THREAD

**Issue by VladimirVecera** [arduino/arduino-ide#665]
I use multiple files in the project and unfortunately after upgrading from beta 11 to RC1 I have a problem with the open file names in the project. In addition to the name, the path is also displayed, so the whole tab is nonsense. 

**Screenshots**
![image](https://user-images.githubusercontent.com/64955913/144643289-9fae01ad-de91-4cdc-a268-02aa54657994.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Version:  RC1

**Comment by per1234** [comment]
Hi @VladimirVecera. Thanks for your report! I also have noticed this change, but I have only observed it while I am experiencing this bug: https://github.com/arduino/arduino-ide/issues/656. The duplicate tabs bug occurred prior to https://github.com/arduino/arduino-ide/pull/610, but before that the duplicated tabs only had the file name.

Please provide a detailed set of instructions we can follow to reproduce the issue.

Does this issue occur for you with any sketch (e.g., **File > Examples > 01.Basics > Blink**), or it is only a specific sketch? If the latter, please attach the sketch in a reply here as a `.zip` file.

**Comment by VladimirVecera** [comment]
If I open any example from the library, the name in the tab works fine. Only the name is displayed.

However, if I open any sketch, its path will always be displayed in addition to the file name.

**Comment by per1234** [comment]
What is the technique you use to open the sketch @VladimirVecera?

**Comment by VladimirVecera** [comment]
This is my video with problem tab:
https://user-images.githubusercontent.com/64955913/144704488-7b5f68d3-cf38-4713-8eac-8fed966699af.mp4

**Comment by per1234** [comment]
Thanks. That is useful. I can see the duplicated tabs:

![image](https://user-images.githubusercontent.com/8572152/144704974-4b273a3d-4ed0-433c-a1ed-f31300c18004.png)

so you are experiencing https://github.com/arduino/arduino-ide/issues/656. But I'll leave this open because I think we should keep an eye out for valid conditions under which this unhelpful path is shown in the tab.

I have only experienced [this problem](https://github.com/arduino/arduino-ide/issues/656) while opening sketch files from the "**Sketchbook**" sidebar panel. I don't think you will have the problem if you open sketches using **File > Sketchbook** or **File > Open** or **File > Recent**.

**Comment by VladimirVecera** [comment]
More detail. After opening the sketchbook, the tab will load fine. But as soon as I click the mouse on the project, the path is added to the tab.

https://user-images.githubusercontent.com/64955913/144705297-d67b7f03-e1b1-4847-8b4d-92aea822b1d1.mp4

**Comment by per1234** [comment]
There is another report of the path in the tab text here:

https://forum.arduino.cc/t/ide-2-0-0-rc2-inconsistent-tab-naming/936096

This time it is happening with the last open sketch that opens automatically on startup in the Arduino IDE, and only on every other startup. I haven't been able to reproduce that variant yet.

**Comment by per1234** [comment]
Another report here:

https://forum.arduino.cc/t/very-incorrect-display-in-the-tab-line/938102

**Comment by per1234** [comment]
One of the several things that can cause this issue is upgrading from Arduino IDE 2.0.0-beta.11

1. Start [Arduino IDE 2.0.0-beta.11](https://github.com/arduino/arduino-ide/releases/tag/2.0.0-beta.11)
1. Quit Arduino IDE 2.0.0-beta.11
1. Start a newer version of the Arduino IDE.
   The last sketch is opened with duplicated tabs.

**Comment by per1234** [comment]
The developers have made multiple changes that should fix this issue:

- https://github.com/arduino/arduino-ide/pull/1012
- https://github.com/arduino/arduino-ide/pull/1024
- https://github.com/arduino/arduino-ide/pull/1085
