### ISSUE TITLE
Pulled remote sketches don't show error underlines and markers

### ISSUE THREAD

**Issue by 91volt** [arduino/arduino-ide#669]
**Describe the bug**
When working on a sketch pulled from the cloud the user doesn't get any error marker/underline in the code editor. It makes a lot difficult to debug and troubleshoot the remote sketch.

**To Reproduce**

1. Go to web editor at [https://create.arduino.cc/editor](https://create.arduino.cc/editor) and Login
2. Open blink example clicking the voice from left sidebar 'example' > '01. BASICS (6)' > 'blink.ino'
3. Try to modify the sketch and when prompted by the dialog box save it as 'blink_test'
4. Delete the last semicolon at line 36
5. Open the IDE 2 software
6. Go to sketchbook explorer clicking the first voice on left sidebar
7. Open remote sketchbooks clicking on 🌐 tab in the sidebar
8. Pull 'blink_test' clicking on down arrow icon on the right of the sketch's name
9. Open the pulled sketch double clicking on 'blink_test' on the sidebar
10. Try to verify -> it will give an error but no red underline at the end of line 36
11. Save the sketch locally pressing CMD/Ctrl + Shift + S, save it in Arduino folder.
12. Check line 36 and you will see the error underline where the semicolon is missing.

**Expected behavior**
I expect to see the same behaviour of local sketches: if an error is present in the code I expect it to be red underlined and a red marker to be present in the scrollbar area in the far right.

**Screenshots**
<img width="1436" alt="missing_cloud_errors" src="https://user-images.githubusercontent.com/92443068/144988085-8a11f81f-77e4-4dfc-b860-f948fc0a8141.png">

**Desktop (please complete the following information):**
- OS: All
- Version: 2.0.0 beta 12

**Additional context**
It seems not caused by a language server crash

**Comment by per1234** [comment]
An update: as of https://github.com/arduino/arduino-ide/pull/1107, the "problems" (AKA "diagnostics") feature this issue applies to is disabled by default. This means that the underlines would not be shown even if the feature was working correctly for remote sketches.

In order to reproduce the issue you must first enable the feature:

1. Open the "**Command Palette**" (<kbd>Ctrl</kbd>/<kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>).
1. Select the "**Preferences: Open Settings (UI)**" command from the "**Command Palette**".
   The "**Preferences**" tab will now open in the editor panel.
1. In the "**Search Settings**" field, type `arduino.language.realTimeDiagnostics`
1. Check the checkbox under the "**Arduino › Language: Real Time Diagnostics**" section if it is unchecked.
