### ISSUE TITLE
Language server results not updated after changes to installed libraries

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#670]
## Describe the bug

The information provided by the Arduino language server is affected by the dependencies used by the sketch.

🐛 The lack of an update of the language server results after a change is made to the installed libraries or platforms (i.e., install, update, or uninstall) may cause them to be incorrect.

## To Reproduce

1. Open the following sketch in the Arduino IDE:
   ```cpp
   #include <Arduino_APA102.h>
   Arduino_APA102 leds(1, 2, 3);
   void setup() {}
   void loop() {}
   ```
   If the library is not installed, problems will be indicated as expected.
1. Install the "Arduino_APA102" library via Library Manager.

🐛 The problems are still indicated even though the sketch is now valid:

![image](https://user-images.githubusercontent.com/8572152/144994962-a669fc3e-a38e-4997-8268-cfe25aa7680c.png)

If you trigger an update by reopening the sketch, changing the code, etc., the language server results update and reflect the current state of the sketch's dependencies.

## Expected behavior

Language server results are updated after making any change to installed libraries via the IDE interface:

- Boards Manager
- Library Manager
- **Sketch > Include Library > Add .ZIP Library...**
- **File > Preferences > Sketchbook location**

## Desktop

- OS: Windows 10
- IDE Version: 2.0.0-rc1-snapshot.be55a0a
Date: 2021-12-03T11:09:57.266Z
CLI Version: 0.20.1 [abb21449]
- [Arduino Language Server](https://github.com/arduino/arduino-language-server) version: 0.5.0-rc6

**Comment by cmaglie** [comment]
With version 0.5.0-rc6 of the LS, the error disappears as soon as the user touch (makes a change) in the source code. This means that the LS needs a signal from the IDE that something changed in the global installation, so to fix this issue we need changes in the IDE.

I see only two possible solutions to this problem:

a) the IDE must restart the language server after each install/uninstall operation (this may be forced by running the command "Arduino: restart language server" from the command palette)

b) the IDE must send a "rebuild" command in some way to the language server

I personally prefer the solution "b" because restarting the language server is an expensive operation. The problem is that there is nothing like a "rebuild" command in the LSP (language server protocol). A workaround could be to produce a bougs "textDocument/didSave" event (that do not actually save anything) that in turns triggers a rebuild on the LS.

**Comment by kittaakos** [comment]
> I personally prefer the solution "b" because restarting the language server is an expensive operation.

👍 This seems to be the proper way.

> The problem is that there is nothing like a "rebuild" command in the LSP (language server protocol)

FYI, it's possible to extend it, if you decide to do so in the future. Here is the Java example from VS Code to the JDT-LS:
 - VS Code: https://github.com/redhat-developer/vscode-java/blob/c0d043e53057550e3075713f9c2f2d0fdc4902cf/src/standardLanguageClient.ts#L337-L338
 - LS: https://github.com/eclipse/eclipse.jdt.ls/blob/791f30ed63f9960d5ad7dc2e9ba3b9e203cf2b9a/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java#L68-L69

> "textDocument/didSave"

Or with [`textDocument/didChange`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_didChange) with an empty `contentChanges` but with an increased `version` number.

**Comment by ubidefeo** [comment]
@kittaakos @cmaglie 
what's the status of this issue?
