### ISSUE TITLE
Opening another Sketch starts a second instance of the IDE instead of showing the second Sketch in a new tab

### ISSUE THREAD

**Issue by JonasTaulienSolutions** [arduino/arduino-ide#691]
**Describe the bug**
Opening another Sketch starts a second instance of the IDE instead of showing the second Sketch in a new tab

**To Reproduce**
1. Open a Sketch
2. Do one of the following:
    * Double click on a different Sketch in the Sketchbook
    * File > Open > Select File
3. Arduino IDE will open the selected Sketch a new instance of itself

**Expected behavior**
Arduino IDE will open the selected Sketch in a new tab

**Desktop (please complete the following information):**
OS: macOS 10.15.7
Version: 2.0.0-rc2
Date: 2021-12-13T10:10:06.858Z
CLI Version: 0.20.2 [13783819]

**Comment by per1234** [comment]
Hi @JonasTaulienSolutions. Thanks for taking the time to submit an issue.

This is the intentional design of the Arduino IDE. Even though many sketches consist of only a single file, the `.ino` file is not the sketch. The sketch is the entire project folder, which may contain many source files. All those files are compiled into a single program. For this reason, it would be very confusing to have multiple sketches open in the same window. This is why the IDE uses a dedicated window for each sketch you have open.
