### ISSUE TITLE
Error when extracting the zip file

### ISSUE THREAD

**Issue by Pius171** [arduino/arduino-ide#703]
**Describe the bug**
I got an error when extracting the files 

**To Reproduce**
just try extracting the arduino 2.0 zip file

**Desktop (please complete the following information):**
 - OS: [ Windows 10]

![image](https://user-images.githubusercontent.com/70412012/146655748-48dc969f-6be9-460b-bad6-c523e05e884d.png)

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @Pius171 .

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/106.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

---

I'll share some advice for working around the problem:

- Try using one of the Windows installer versions of the IDE instead of the ZIP version
- Install the IDE under a shorter path (e.g., `C:\` instead of `C:\my stuff\other stuff\arduino stuff\arduino ides that i use all the time\arduino ide 2\`)
