### ISSUE TITLE
No icon in the latest version

### ISSUE THREAD

**Issue by dominpiano** [arduino/arduino-ide#735]
There is no app icon in the latest version of Arduino 2.0.0, and there is no possibility to adjust the height of the output.

**Comment by per1234** [comment]
Thanks for your report @dominpiano.

We are going to need more details in order to investigate this.

Which operating system are you using?

>there is no possibility to adjust the height of the output.

What do you mean by "output"?

If you mean the bottom panel where the Output view is, this is how it works for me:

![screencast](https://user-images.githubusercontent.com/8572152/148096185-a03bc1e6-4dff-46fa-91ac-77c1f012e5de.gif)

Are you experiencing something different from that? If so, please provide a detailed description. Include screencast or screenshot if appropriate.

**Comment by dominpiano** [comment]
Okay, this was some temporary bug, maybe from first open of the program, now I have this possibility. Probably I have no icon on this app because the same issue of some problems during installation. 
Thanks a lot
