### ISSUE TITLE
The board can't download on board maneger, "Archive format not supported" 

### ISSUE THREAD

**Issue by 0hotpotman0** [arduino/arduino-ide#737]
**Describe the bug**
I made a new board that is working fine on my PC. And I upload my board info to a Seeed JSON, that is the link:  https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json

But there is a problem when I download my board on another PC.

**Screenshots**
![image](https://user-images.githubusercontent.com/47217650/148171707-d91132f8-08a1-4d57-a848-aae7c48db932.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: [1.8.15]

**Additional context**

**Comment by per1234** [comment]
Hi @0hotpotman0. The reason for this error is the archive format of this file:

https://files.seeedstudio.com/arduino/core/nRF52840/Seeed_XIAO_BLE_nRF52840_Sense.rar.bz2

This is a `.rar.bz2`, but that is not supported, so the error is valid.

This is documented here in the Arduino Package Index Specification:

https://arduino.github.io/arduino-cli/0.20/package_index_json-specification/#installation-archive-structure

> Supported formats are .zip, .tar.bz2, and .tar.gz.

So you should create the archive again, this time making it a `.tar.bz2` file instead of `.rar.bz2` (note **t**ar vs **r**ar). Make sure to update the  also update the `url`, `archiveFileName`, `checksum`, and `size` fields of the package index accordingly.

While you are at it, I have some additional suggestions, unrelated to the error you encountered, but that I think might be beneficial:

- Don't put the Git repository in the archive. This is adding 721 MB to the size of the installation that the IDE doesn't use and most users won't have an interest in. This will make the installation take far longer and put an unnecessary load on Seeed's server. I think it is great if you want to publish the repository, but that is better done on GitHub than through Boards Manager.
- Check the `architecture` field value for this platform in the package index. It is currently set to `nrf32`, but I'm pretty sure it was intended to be `nrf52` instead.
