### ISSUE TITLE
"Upload SSL Root Certificates" does not recognize my Arduino board

### ISSUE THREAD

**Issue by Givy** [arduino/arduino-ide#775]
**Describe the bug**
Can't select/see ports on connected Arduino boards: "Upload SSL Root Certificates";; "1. Select certificate to upload".  Can't make selection everything grayed out.

**To Reproduce**

1. Go to 'start Arduini IDE 2.0.0Rc3, Tools, ...'
2. Click on 'WiFi101 / WiFiNINA Firmware Updater, 
Select Board. Can't make any selection and everything is greyed out.'

**Expected behavior**
Installed Arduino IDE when it came out about 2 years ago. Was working but was not interesting.  Just uninstalled and installed the latest arduino-ide_2.0.0-rc3_64bit.  Can't get it started.  Can't see my boards and doesn't give you options or selections on the port which Arduino boards are connected to.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]  Windows 10 Pro 
 - Version: [e.g. 2.0.0] 21H2

**Comment by per1234** [comment]
Hi @Givy. Thanks for your report.

Which Arduino board are you using?

Are you able to see the port of your Arduino board in the "**Ports (COM & LPT)**" section of the [Windows **Device Manager**](https://support.microsoft.com/en-us/windows/open-device-manager-a7f2db46-faaf-24f0-8b7b-9e4a6032fc8c)?

Do you see it in the **Tools > Port** menu of the Arduino IDE?

**Comment by Givy** [comment]
Hi, Thanks for your prompt response.

I have a Mega 2560 an UNO and a DUE.  
I do see the ports under the device manager usually as port COM3and COM6 when I connect them to the PC.  Thats not any issue.  But nothing shows when I try to select the ports under Tools> Port with the 'arduino-ide_2.0.0-rc3_64bit up'.  The previous version didn't have that issue.  This one asks for "Upload SSL Root Certificates", "1. Select certificate to upload" but can't change anything.  Let me know.
Many Thanks.
Givi

**Comment by per1234** [comment]
>I have a Mega 2560 an UNO and a DUE.

OK, then what you are observing with the "**WiFi101 / WiFiNINA Firmware Updater**" and "**Upload SSL Root Certificates**" features of the IDE is expected and normal. These tools only list supported boards and the boards you are using are not supported because they do not have Wi-Fi radio modules. For this reason, they have no use for your boards and so you aren't missing out on anything by not being able to use them.

The "**WiFi101 / WiFiNINA Firmware Updater**" and "**Upload SSL Root Certificates**" features of the IDE are for use with the Wi-Fi enabled official Arduino boards. For example:

- [Nano 33 IoT](https://store.arduino.cc/arduino-nano-33-iot)
- [MKR WiFi 1010](https://store.arduino.cc/arduino-mkr-wifi-1010)
- [MKR1000](https://store.arduino.cc/arduino-mkr1000-wifi)
- [Uno WiFi Rev2](https://store.arduino.cc/arduino-uno-wifi-rev2)

---

If you need any assistance using your Mega 2560, Uno, or Due boards, feel free to ask over on the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/

**Comment by Givy** [comment]
Hi,
Thanks again.  I most likely miss spoke.  I should have said under the 'WiFi101 / WiFiNINA Firmware Updater, please see the screen shots attached.  With Arduino 1.8.1.9 you see the ports.  Let me know.  I hope this helped.
Thank you.
Givi

![arduino-1 8 1 9](https://user-images.githubusercontent.com/15314129/151460907-e25b2a91-69a5-41d2-b4d4-99d8076eb9ad.png)
![arduino-ide_nightly-20220125_Windows_64bit](https://user-images.githubusercontent.com/15314129/151460909-99023b4b-643c-4611-a411-31563328e52c.png)
![arduino-ide_nightly-20220125_Windows_64bit-No Port](https://user-images.githubusercontent.com/15314129/151460911-82cd942a-4724-44b2-a252-da50238524fc.png)

**Comment by Givy** [comment]
Hi,

Please make sure you see the screen shots that I sent you before closing this case.

Regards,

Givi



________________________________
