### ISSUE TITLE
Use separate tooltip for status icon in board selection drop-down

### ISSUE THREAD

**Issue by RussellAult** [arduino/arduino-ide#85]
**Is your feature request related to a problem? Please describe.**
This is pretty minor (and perhaps more difficult to achieve than it's worth, especially in the context of what I'm sure is inevitably-forthcoming documentation), but as it stands I have absolutely no clue what the red "X" in the board selection drop-down actually means, and the tooltip when I hover over the "X" is the same as for the rest of the drop-down (i.e. the un-trunkated name of the board).

**Describe the solution you'd like**
A separate tooltip for the status icon describing its meaning would be great!

**Describe alternatives you've considered**
As mentioned above, presumably somewhere down the road the status icon's meaning will be made clear in documentation, but even in that context I think the tooltip would still be useful.

**Comment by per1234** [comment]
Related: https://github.com/arduino/arduino-ide/issues/200

**Comment by per1234** [comment]
Closing as fixed by https://github.com/arduino/arduino-ide/pull/1193

The ❌ is no longer used to indicate a disconnected state.

A tooltip is now used to communicate the connection state to the user:

![image](https://user-images.githubusercontent.com/8572152/179683385-96b47185-611c-4799-860d-e5e08157c0ae.png)

Thanks so much for your excellent feedback and suggestion @RussellAult!
