### ISSUE TITLE
[ INFO ] Debug functionality: an update

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#87]
We have received a lot of confusing requests from users who had issues with the Debug feature of this new IDE,
From hard to decipher errors to unsupported hardware.

We are aware of the fact that such functionality can create confusion in both novice and advanced users, so the team and I decided to put together this update.

As we move towards a Beta release (it will be announced when we feel comfortable with giving it the monicker), we have been investigating the behaviour of the included debugger and plan to offer a much better working solution in the near future.
Please try not to ask "are we there yet" every week, just know that we're at work and we're not a big team.

A better debugger is coming, we look forward to releasing it into your hands, but we want it to be good :)

For the current debugger functionality you have to know the following:

* not every board is supported, in fact only ARM Cortex based boards can work
* our current lineup (MKR, Nano 33, Portenta H7) has support, somewhere it's flaky
* [support for debug (a debug recipe)](https://arduino.github.io/arduino-cli/latest/platform-specification/#sketch-debugging-configuration) must be provided by the platform developer, so please don't ask us to enable debug for boards which we have no control over
* You CANNOT debug an Arduino UNO or a classic Nano
* in the current version of the debugger Global variables are not working and setting booleans fails miseraby: the solution is on its way
* you cannot step into library code, and also this is going to work when we release an update for the debug functionality
* such update will not necessarily come at the next minor Alpha release

Last but not lease: we know that the debug button in the UI is active no matter which board you select, and we're working on this because we don't like it either 😬 

Please feel free to ask more questions below, we're more than happy to update this issue and help you get more clarity.

Thank you for reading us
Arduino Tooling Team

**Comment by DeqingSun** [comment]
The tested the Uno setup for Pro IDE also works for the IDE 2.0. And the 2.0 can choose the board automatically (I guess using PID/VID?), which make things even more easier.

**Comment by ubidefeo** [comment]
@DeqingSun 
does it mean you managed to make it work?

**Comment by DeqingSun** [comment]
> @DeqingSun 
> does it mean you managed to make it work?

yes it works perfectly.

**Comment by SomeGeek** [comment]
@DeqingSun Does your solution also work with the Atmel-ICE? If not, it would be great to have some documentation on the debug hooks. 

That way we could just use AVaRICE to spawn the GDB server and let the IDE connect to it.

**Comment by ubidefeo** [comment]
happy to see you join the conversation, @SomeGeek ;)

**Comment by DeqingSun** [comment]
> @DeqingSun Does your solution also work with the Atmel-ICE? If not, it would be great to have some documentation on the debug hooks.
> 
> That way we could just use AVaRICE to spawn the GDB server and let the IDE connect to it.

I don't think my setup will work with Atmel-ICE. And I've never used AVaRICE.


You can check [this repo](https://github.com/DeqingSun/unoDebugTestPackage) to see how it works. The configuration is in platform.txt and board.txt. As I mentioned before, the debugger module in Arduino IDE will call the debugger server with ```"-c" "gdb_port 50000" "-s" "/Users/sundeqing/Documents/Arduino/testDebug" "-f"```, you may need to modify AVaRICE to accommodate such parameters or run another program as the middle-man to deal with it.

**Comment by SomeGeek** [comment]
@DeqingSun great, I will check into it next week and report back.
@ubidefeo It would be nice if this would be easily adjustable. For example, have an option called `debug_server_params` (eventually with variables such as the compiled binary) and something like `debug_server_port`. These are just examples. That way it would be much more flexible for others to use implement their own configs.

**Comment by ubidefeo** [comment]
@SomeGeek 
you should be able to override and add any option for the generated configuration via a `debug_custom.json` file in the Sketch folder.
I have mentioned this above
https://github.com/arduino/arduino-ide/issues/87#issuecomment-774362701

**Comment by tigoe** [comment]
I'm excited to see this, and excited to see @DeqingSun contributing to it. It will take some really good documentation to make sure beginners in the IDE 2.0 don't mess up their SAMD boards by trying to use the debugger. I would suggest two things:

* Some clear documentation, written for beginners, on how to use the debugger (@DeqingSun's repo is a good starting place)
* Good error messages that let you know when the debugger might be getting in the way of your non-debugger-related development, and how to resolve it. For example:

1. Open a new sketch
2. Open debugger
3. Add a new configuration, don't put anything in it
4. Switch back to the sketch tab, upload

This is as good a way as any I've found to make your SAMD-based board totally unresponsive, and there's no error message telling you what you did wrong. And it's likely the default behavior for someone who's never used a debugger (feel free to move this to a more appropriate thread, @ubidefeo )

**Comment by SomeGeek** [comment]
I finally got some time to continue with this.

Using the packages @DeqingSun provided and the prepared digispark, I was able to get it to debug on VSCode. On the Arduino IDE however, clicking launch spawns a cursor inside launch.json with a selection of debug templates (and I already have defined one).

The same happens using an modified avarice build which corrects the parameters.

**Comment by per1234** [comment]
Hi @SomeGeek 
> clicking launch spawns a cursor inside launch.json with a selection of debug templates (and I already have defined one). I don't know what I'm missing.

The interface of the debugger is not yet as user friendly and intuitive as we would like. It is essential that you initialize the debugger by clicking the "**Start Debugging**" button on the button bar:

![image](https://user-images.githubusercontent.com/8572152/152126318-d606b170-064f-41f9-9b46-2fcc1c1b98d0.png)

The "**Debug**" button on the activity bar should only be used for toggling the visibility of the debugger panel.

If you open the debugger via the "**Debug**" button on the activity bar without first clicking the "**Start Debugging**" button on the button bar, then the debugger is unconfigured. If you then click the "**Start Debugging**" button (<kbd>**▷**</kbd>) in the "**DEBUG**" view, it creates an empty `.theia/launch.json` file in the sketch and opens that file in the editor, as you experienced already.

In order to make debugging accessible to the target user, the Arduino IDE automagically generates a `launch.json` file in the temporary build folder when the debugger is initialized. This file is configured for the board you currently have selected in the Arduino IDE, according to the properties set in the [Arduino boards platform](https://arduino.github.io/arduino-cli/latest/platform-specification/) of that board. For this reason, the `.theia/launch.json` file is completely ignored, and thus this file the unconfigured debugger creates is a dead end when it comes to configuring the debugger.

Even though it is possible to override all keys under `configurations[0]` in the auto-generated `launch.json` by adding a `debug_custom.json` file to your sketch, the IDE still requires the platform of the currently selected board to contain a full debugging configuration, like how it is done in the "**Arduino SAMD (32-bits ARM Cortex-M0+) Boards**" platform here:

https://github.com/arduino/ArduinoCore-samd/blob/1.8.12/platform.txt#L129-L140

The IDE is smart enough to disable the "**Start Debugging**" button on the button bar if the platform does not define a `debug.executable` property, but all the other properties you see at the link above are also required for the debugger to actually be initialized. If any are missing, you will get no apparent reaction from clicking that button.

**Comment by DeqingSun** [comment]
Some update about Uno debugging. 

I've tested Arduino 2.0.0/2.0.1 in a class and the IDE worked very well with ATMega328P with the [board support](https://github.com/DeqingSun/unoDebugTestPackage/tree/main). The students can debug the ATMega328P and see how the code works.

The "Request 4 cancelled on connection closed" error appeared once while I did the demo and it was fixed with the [method](https://forum.arduino.cc/t/getting-the-debugger-to-work/1020797/8) mentioned in the Arduino Forum. Not sure the root of cause but maybe related to some settings.

**Comment by per1234** [comment]
>The "Request 4 cancelled on connection closed" error appeared once while I did the demo and it was fixed with the [method](https://forum.arduino.cc/t/getting-the-debugger-to-work/1020797/8) mentioned in the Arduino Forum.

Hi @DeqingSun there is a known bug that can cause this error:

https://github.com/arduino/arduino-ide/issues/1582

A more convenient workaround is described under the "Additional context" section of that issue.

**Comment by per1234** [comment]
> - in the current version of the debugger Global variables are not working and setting booleans fails miseraby: the solution is on its way
> - you cannot step into library code, and also this is going to work when we release an update for the debug functionality

These defects were fixed long ago (perhaps by https://github.com/arduino/arduino-ide/commit/e7b1a27401f6aa0457ce451ca4f39a255bfac1a7).

>the debug button in the UI is active no matter which board you select

Fixed by https://github.com/arduino/arduino-ide/commit/e7b1a27401f6aa0457ce451ca4f39a255bfac1a7
