### ISSUE TITLE
Double clicking ino file doesn't open it

### ISSUE THREAD

**Issue by Ali229** [arduino/arduino-ide#877]
**Describe the bug**
When double clicking an ino sketch file, the IDE disregards what is being clicking on and instead loads a file that was loaded previously. Have to manually go into File>Open>Select the file to load it.

**To Reproduce**
1. Double click an ino file
2. IDE instead opens the sketch that was loaded previously

**Expected behavior**
1. Load the sketch that was clicked on

**Desktop:**
 - OS: Windows 10
- Arduino 2.0 RC3

**Comment by per1234** [comment]
Hi @Ali229. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/370.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

You'll be happy to learn that file association capabilities have been added since the time of the 2.0.0-rc3 release you are using.
