### ISSUE TITLE
Better manager of installed libraries

### ISSUE THREAD

**Issue by VladimirVecera** [arduino/arduino-ide#938]
### Describe the request

Is it possible to include a filter in the library overview in the future? For example, show only installed or who received an update? I have also noticed that not all arduino libraries as such gives users a view. Many of them are needed on Github.com, but they are not included in the Arduino library itself. Make some central database. 

### Describe the current behavior

It is poorly searched in libraries. 

### Arduino IDE version

RC5

### Operating system

Windows

### Operating system version

Windows10

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @VladimirVecera. Thanks for taking the time to submit an issue.

>Is it possible to include a filter in the library overview in the future? For example, show only installed or who received an update?

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/177.

>I have also noticed that not all arduino libraries as such gives users a view. Many of them are needed on Github.com, but they are not included in the Arduino library itself. Make some central database.

There is a known bug that causes the Library Manager search results to be incomplete when there are a lot of results:

https://github.com/arduino/arduino-ide/issues/716

If you instead are referring to the fact that not all 3rd party Arduino libraries are in the Arduino Library Manager at all, that is because they are submitted by the community, so the library will only be in the Library Manager if someone from the community made the submission already. Everyone is welcome to submit missing libraries. You can learn how to do that here:

https://github.com/arduino/library-registry#adding-a-library-to-library-manager

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the others.

If you end up with additional information to share, feel free to comment in the other threads.
