### ISSUE TITLE
"ctrl+T" changes the braces position I HATE that

### ISSUE THREAD

**Issue by Ma5t3rful** [arduino/arduino-ide#94]
after auto-fomating in Arduino Pro IDE. It changes the braces position (but legacy IDE doesn't):
![image](https://user-images.githubusercontent.com/37829730/92239471-5121cf80-eed0-11ea-9063-e6ae2760321b.png)

**Comment by tigoe** [comment]
I didn't quite follow your description of how to switch from clang to artistic style, but I would like to request that this be made as easy as possible. The artistic style is one of the things I quite liked about the Processing style we started with, and I will miss it when I finally have to switch to 2.0.

**Comment by per1234** [comment]
>I didn't quite follow your description of how to switch from clang to artistic style

There is nothing at all the user needs to do to switch. It is integrated into the Arduino IDE 2.x. Simply use the auto format functionality just as you do with Arduino IDE 1.x.

The information I shared above is for any advanced users who happen to have their own formatting style preferences (e.g., "broken" instead of "attached" braces) and want to configure the Arduino IDE 2.x formatter to work differently than it does by default.

>I would like to request that this be made as easy as possible

We plan to clearly and thoroughly document the formatter configuration system (something that was never done for Arduino IDE 1.x). I have left https://github.com/arduino/arduino-ide/issues/42 so that we can track that remaining task.

**Comment by tigoe** [comment]
I'm still getting some strange behavior on the autoformat. Steps to repeat it on Windows 11 and 2.0.0 rc6:

1. Type in the following (wrong spacing shown):

````
void setup() {
  // put your setup code here, to run once:
for (int p = 2; p < 6; p++) {
pinMode(p, OUTPUT);
}
Serial.begin(9600);
}
````

2. type ctrl-T
3. nothing happens. 
5. Switch to another app
6. Switch back to Arduino IDE
7. file auto-formats to the following:
````
void setup() {
  // put your setup code here, to run once:
  for (int p = 2; p < 6; p++) {
    pinMode(p, OUTPUT);
  }
  Serial.begin(9600);
}
````

So the artistic formatting seems to be back, but it doesn't do it on ctrl-T, it does it on app switching -- or perhaps on some timed file update? Can't tell, but I'll try on MacOS this afternoon.

**Comment by per1234** [comment]
Thanks for testing @tigoe.

A very important improvement was made to the formatter system last week: https://github.com/arduino/arduino-ide/pull/1019. That should fix the problem you encountered (the cause is explained here: https://github.com/arduino/arduino-ide/issues/1009).

That fix is currently only available from the nightly build of the Arduino IDE. The download links to the nightly build are here:

https://github.com/arduino/arduino-ide#nightly-builds

Some really amazing advancements were made yesterday, which are not currently available in the nightly build. If you would like the latest and greatest, it is currently available from the links under the "**Assets**" section of this page:

https://github.com/arduino/arduino-ide/actions/runs/2455017636#artifacts

You must be signed in to your GitHub account in order for those specific download links to be active (a limitation imposed by GitHub).

**Comment by tigoe** [comment]
Beautiful!

Test: Wrote a complex sketch with no tabs. Every few seconds it would auto-tab correctly for the artistic format. When I reached the end, I ctrl-T and it all formatted immediately and correctly. 

Nice work, thank you!
